insert into produse (cod, denumire) values(437,'HP Color Cartridge DJ400/500 series');
insert into produse (cod, denumire) values(438,'DeskJet 960C, A4, 2400x1200dpi, 8MB');  
insert into produse (cod, denumire) values(439,'Toner for LJ4000 ( C4127A )'); 
insert into produse (cod, denumire) values(440,'LaserJet 1200, A4, 1200 dpi, 8MB, Postscript 2');  
insert into produse (cod, denumire) values(441,'ScanJet 5400C, 2400dpi');  
insert into produse (cod, denumire) values(442,'ScanJet 7450C, 2400dpi, transparenta, ADF');  
insert into produse (cod, denumire) values(443,'ScanJet 3400C, 600dpi');  
insert into produse (cod, denumire) values(444,'LaserJet 3200, printer, scaner, copiator, fax, 1200 dpi, 8MB');  
insert into produse (cod, denumire) values(445,'LaserJet 1220, imprimanta, scaner, copiator, A4, 1200 dpi, 8MB, Postscript 2');  
insert into produse (cod, denumire) values(446,'ScanJet 2200C, 600dpi');  
insert into produse (cod, denumire) values(447,'PSC-750, imprimanta, scaner, copiator color, 2400x1200 dpi');  
insert into produse (cod, denumire) values(448,'LaserJet 4100, A4, 1200dpi, 16M RAM, Postscript 3');  
insert into produse (cod, denumire) values(449,'ScanJet 7400C, 2400dpi, transparenta');  
insert into produse (cod, denumire) values(450,'LaserJet 4100DTN, A4, 1200dpi, 32MB, Postscript 3, duplex, tava suplimentara, network');  
insert into produse (cod, denumire) values(451,'LaserJet 8150N, A3, 1200dpi, 32MB, PostScript 3, network');  
insert into produse (cod, denumire) values(452,'LaserJet 2200DTN, A4, 1200dpi, 16MB, Postscript 2, duplex, tava suplimentara, network');  
insert into produse (cod, denumire) values(453,'ScanJet 4400C, 1200dpi');  
insert into produse (cod, denumire) values(454,'LaserJet 4550N, laser color, A4, 600dpi, 64MB, Postscript 3, network');  
insert into produse (cod, denumire) values(455,'LaserJet 4100N, A4, 1200dpi, 32MB, Postscript 3, network');  
insert into produse (cod, denumire) values(456,'LaserJet 4550, laser color, A4, 600dpi, 64MB, Postscript 3');  
insert into produse (cod, denumire) values(457,'LaserJet 8550, laser color, A3, 600dpi, 32MB, Postscript 3');  
insert into produse (cod, denumire) values(458,'LaserJet 5000, A3+, 1200dpi, 4MB, Postscript 2');  
insert into produse (cod, denumire) values(459,'ThinkPad i 1200 P700/64MB/20GB/13.3"TFT/DVD8X/audio/WinME');  
insert into produse (cod, denumire) values(460,'Pentium 4 1.9 GHz BOX');  
insert into produse (cod, denumire) values(461,'Celeron 700 MHz'); 
insert into produse (cod, denumire) values(462,'Pentium 4 1.8 GHz BOX');  
insert into produse (cod, denumire) values(463,'Pentium 4 1.7 GHz tray');  
insert into produse (cod, denumire) values(464,'Celeron 850 MHz');  
insert into produse (cod, denumire) values(465,'Pentium 4 1.4 GHz BOX');  
insert into produse (cod, denumire) values(466,'Pentium 4 1.6 GHz BOX');  
insert into produse (cod, denumire) values(467,'Celeron 800 MHz');  
insert into produse (cod, denumire) values(468,'Celeron 900 MHz');  
insert into produse (cod, denumire) values(469,'Pentium 4 1.7 GHz BOX');  
insert into produse (cod, denumire) values(470,'Pentium 4 1.5 GHz BOX');  
insert into produse (cod, denumire) values(471,'Celeron 1000 MHz BOX');  
insert into produse (cod, denumire) values(472,'Pentium 4 1.5 GHz BOX Socket 478');  
insert into produse (cod, denumire) values(473,'Jaz Traveller, Paralel Adapter');  
insert into produse (cod, denumire) values(474,'Adaptor Clik! Dock');  
insert into produse (cod, denumire) values(475,'Unitate ZIP 100MB, intern, ATAPI');  
insert into produse (cod, denumire) values(476,'Unitate ZIP 100MB, extern, USB');  
insert into produse (cod, denumire) values(477,'PREDATOR CD-RW 4x/4x/6x, externa portabila, USB, retail');  
insert into produse (cod, denumire) values(478,'Unitate ZIP 250MB, PARALEL, extern');  
insert into produse (cod, denumire) values(479,'Quik Sync, backup software');  
insert into produse (cod, denumire) values(480,'Unitate JAZ 2GB, SCSI, intern');  
insert into produse (cod, denumire) values(481,'Unitate ZIP 250MB, ATAPI, intern');  
insert into produse (cod, denumire) values(482,'Clik! PC Card Drive 40MB PCMCIA');  
insert into produse (cod, denumire) values(483,'Unitate ZIP 250MB, USB, extern');  
insert into produse (cod, denumire) values(484,'Unitate Magneto-Optica 1.3GB, SCSI, intern');  
insert into produse (cod, denumire) values(485,'CD-RW 4x/4x/6x, externa, USB, retail');  
insert into produse (cod, denumire) values(486,'ZIP DISK 250MB pentru unitati Zip 250MB');  
insert into produse (cod, denumire) values(487,'Mediu de stocare JAZ 1GB');  
insert into produse (cod, denumire) values(488,'Mediu de stocare JAZ 2GB');  
insert into produse (cod, denumire) values(489,'Mediu de stocare magneto-optic 1.3GB');  
insert into produse (cod, denumire) values(490,'Pachet Zip Disk 100MB - 6 bucati multicolore');  
insert into produse (cod, denumire) values(491,'Clik! Media 40MB pentru unitati Clik!');  
insert into produse (cod, denumire) values(492,'Jaz Card, PCMCIA Adapter');  
insert into produse (cod, denumire) values(493,'Unitate Magneto-Optica 1.3GB, SCSI, extern');  
insert into produse (cod, denumire) values(494,'Jaz Jet ISA');  
insert into produse (cod, denumire) values(495,'Unitate JAZ 2GB, SCSI, extern');  
insert into produse (cod, denumire) values(496,'ZIP DISK 100MB pentru unitati Zip 100MB/250MB');  
insert into produse (cod, denumire) values(497,'HipZip, Digital Audio Player, Clik Media 40MB, MP3');  
insert into produse (cod, denumire) values(498,'SonicLock');  
insert into produse (cod, denumire) values(499,'MemoryLock si cablu');  
insert into produse (cod, denumire) values(500,'Anchor Point');  
insert into produse (cod, denumire) values(501,'Micro saver');  
insert into produse (cod, denumire) values(502,'Extra Security Plates');  
insert into produse (cod, denumire) values(503,'Desktop MicroSaver');  
insert into produse (cod, denumire) values(504,'FloppyLock');  
insert into produse (cod, denumire) values(505,'MemoryLock');  
insert into produse (cod, denumire) values(506,'Leash');  
insert into produse (cod, denumire) values(507,'ComboSaver');  
insert into produse (cod, denumire) values(508,'Joystick WingMan Attack 2, USB');  
insert into produse (cod, denumire) values(509,'QuickCam Pro 3000');  
insert into produse (cod, denumire) values(510,'Cordless Desktop Optical Kit');  
insert into produse (cod, denumire) values(511,'Volan WingMan Formula Force GP, Force Feeedback, pedale, USB');  
insert into produse (cod, denumire) values(512,'Joystick WingMan StrikeForce 3D, Force Feedback, USB');  
insert into produse (cod, denumire) values(513,'Pilot Mouse, PS/2');  
insert into produse (cod, denumire) values(514,'Mini Wheel Mouse, USB, PS/2');  
insert into produse (cod, denumire) values(515,'Gamepad WingMan Precision');  
insert into produse (cod, denumire) values(516,'QuickCam Express');  
insert into produse (cod, denumire) values(517,'ClickSmart 310, portabila');  
insert into produse (cod, denumire) values(518,'Bundle 2*QuickCam Express');  
insert into produse (cod, denumire) values(519,'QuickCam Web');  
insert into produse (cod, denumire) values(520,'Gamepad WingMan RumblePad, Vibration Feeback, USB');  
insert into produse (cod, denumire) values(521,'Cordless MouseMan Optical, USB, PS/2');  
insert into produse (cod, denumire) values(522,'Cordless Desktop Pro Kit');  
insert into produse (cod, denumire) values(523,'Keyboard Deluxe Access');  
insert into produse (cod, denumire) values(524,'ClickSmart 510, portabila');  
insert into produse (cod, denumire) values(525,'Trackball Cordless TrackMan Wheel, optic, USB, PS/2');  
insert into produse (cod, denumire) values(526,'Cordless Desktop Kit');  
insert into produse (cod, denumire) values(527,'Mouse Cordless Wheel, USB, PS/2');  
insert into produse (cod, denumire) values(528,'Trackball Cordless TrackMan, optic, USB, PS/2');  
insert into produse (cod, denumire) values(529,'Pilot Wheel Mouse Optical, USB, PS/2');  
insert into produse (cod, denumire) values(530,'Internet Navigator Keyboard');  
insert into produse (cod, denumire) values(531,'Joystick WingMan Force 3D, Force Feedback, Twist Handle, USB');  
insert into produse (cod, denumire) values(532,'Volan WingMan Formula GP, pedale, USB');  
insert into produse (cod, denumire) values(533,'iFeel Mouse Optical, USB');  
insert into produse (cod, denumire) values(534,'Joystick WingMan Extreme Digital 3D, Twist Handle, USB');  
insert into produse (cod, denumire) values(535,'Wheel Mouse Optical, USB, PS/2');  
insert into produse (cod, denumire) values(536,'Cordless Desktop iTouch Kit');  
insert into produse (cod, denumire) values(537,'Socket A, K7 VAT+, VIA KT133, FSB200, SDRAM, ATX, UDMA 100, audio');  
insert into produse (cod, denumire) values(538,'Socket 370, 6VA815EP, Intel 815EP, FSB133, SDRAM, ATX, UDMA 100, audio');  
insert into produse (cod, denumire) values(539,'Socket A, K7APRO, VIA KT133A, FSB266, SDRAM, ATX, UDMA 100, audio');  
insert into produse (cod, denumire) values(540,'Socket 370, 6VA694+, VIA 694X, FSB133, SDRAM, ATX, UDMA 100, audio');  
insert into produse (cod, denumire) values(541,'Dischete 3,5" MAXELL');  
insert into produse (cod, denumire) values(542,'Banda DLT-IV');  
insert into produse (cod, denumire) values(543,'CD-RW Media MAXELL');  
insert into produse (cod, denumire) values(544,'CD-R MAXELL');  
insert into produse (cod, denumire) values(545,'CD-R 80 MAXELL');  
insert into produse (cod, denumire) values(546,'CD-R 16x MAXELL');  
insert into produse (cod, denumire) values(547,'CD-R WHITE MAXELL');  
insert into produse (cod, denumire) values(548,'Atlas V, 36.7GB, SCSI Ultra 160, 7200rpm');  
insert into produse (cod, denumire) values(958,'den');  
insert into produse (cod, denumire) values(1,'ATX MIDDLE TOWER M268 300W Pentium 4');  
insert into produse (cod, denumire) values(2,'ATX MIDI TOWER TH-939 250W');  
insert into produse (cod, denumire) values(3,'ATX MIDDLE TOWER CLIO II 300W Pentium 4');  
insert into produse (cod, denumire) values(4,'ATX MIDDLE TOWER DEFENSE II 300W Pentium 4');  
insert into produse (cod, denumire) values(5,'ATX MIDI TOWER C101 300W');  
insert into produse (cod, denumire) values(6,'ATX MIDI TOWER M180 300W Pentium 4');  
insert into produse (cod, denumire) values(7,'ATX MIDDLE TOWER M320 300W Pentium 4');  
insert into produse (cod, denumire) values(8,'ATX MIDDLE TOWER C201 300W Pentium 4');  
insert into produse (cod, denumire) values(9,'ATX MIDDLE TOWER M368 300W Pentium 4');  
insert into produse (cod, denumire) values(10,'SERVER ZH911');  
insert into produse (cod, denumire) values(11,'ATX MIDDLE TOWER M168 300W Pentium 4');  
insert into produse (cod, denumire) values(12,'ATX MIDI TOWER TH-931 250W');  
insert into produse (cod, denumire) values(13,'ATX FULL TOWER B4 300W Pentium 4');  
insert into produse (cod, denumire) values(14,'ATX MIDI TOWER PC220 300W');  
insert into produse (cod, denumire) values(15,'ATX MIDI TOWER PC200 300W');  
insert into produse (cod, denumire) values(16,'ATX MIDI TOWER DEFENSE I 235W');  
insert into produse (cod, denumire) values(17,'ATX MIDI TOWER CLIO I 235W');  
insert into produse (cod, denumire) values(18,'ATX FLEX SAVIOR 150W');  
insert into produse (cod, denumire) values(19,'Motorola 56k PCI');  
insert into produse (cod, denumire) values(20,'Cooler FCPGA');  
insert into produse (cod, denumire) values(21,'Cooler pentru procesoare AMD Duron');  
insert into produse (cod, denumire) values(22,'Cooler pentru procesoare AMD Athlon');  
insert into produse (cod, denumire) values(23,'Cooler pentru procesoare Intel Pentium 4');  
insert into produse (cod, denumire) values(24,'DIMM DDRAM 128MBoÐÛ PC2100');  
insert into produse (cod, denumire) values(25,'DIMM DDRAM 256MB PC2100');  
insert into produse (cod, denumire) values(26,'Sursa 420W pentru Pentium 4');  
insert into produse (cod, denumire) values(27,'RIMM RDRAM 256MB PC800');  
insert into produse (cod, denumire) values(28,'ATX MINI TOWER PISA 150W');  
insert into produse (cod, denumire) values(29,'56k extern, Topic chipset');  
insert into produse (cod, denumire) values(30,'SERVER CF2000 2x400W');  
insert into produse (cod, denumire) values(31,'SERVER ST103 negru 2x400W');  
insert into produse (cod, denumire) values(32,'SERVER ST103 alb 2x400W');  
insert into produse (cod, denumire) values(33,'SERVER ST808 2x300W');  
insert into produse (cod, denumire) values(34,'SERVER ZH911 420W P4');  
insert into produse (cod, denumire) values(35,'Rack-Mountable 19" A450 235W');  
insert into produse (cod, denumire) values(36,'RIMM RDRAM 128MB PC800');  
insert into produse (cod, denumire) values(37,'56k PCMCIA, Cirrus chipset');  
insert into produse (cod, denumire) values(38,'GeForce3 Ti200 64MB TV-OUT');  
insert into produse (cod, denumire) values(39,'GeForce2 Ti 64MB');  
insert into produse (cod, denumire) values(40,'Radeon VE 64MB TV-OUT');  
insert into produse (cod, denumire) values(41,'GeForce2 MX 200 32MB');  
insert into produse (cod, denumire) values(42,'ATX MIDI TOWER TH-731 250W');  
insert into produse (cod, denumire) values(43,'Riva TNT2 M64 32MB');  
insert into produse (cod, denumire) values(44,'ATX MIDI TOWER TH-938 250W');  
insert into produse (cod, denumire) values(45,'ASUS DVD ROM 16X, IDE, retail');  
insert into produse (cod, denumire) values(46,'56k extern, Conexant chipset');  
insert into produse (cod, denumire) values(47,'ATX MIDI TOWER 828SA 235W');  
insert into produse (cod, denumire) values(48,'ATX MIDI TOWER 848SA 235W');  
insert into produse (cod, denumire) values(49,'ATX MIDI TOWER 828CA 300W Pentium 4');  
insert into produse (cod, denumire) values(50,'ATX MIDI TOWER 848CA 300W Pentium 4');  
insert into produse (cod, denumire) values(51,'ATX MIDI TOWER SGM40 300W Pentium 4');  
insert into produse (cod, denumire) values(52,'ATX MIDDLE TOWER TK6006 300W Pentium 4');  
insert into produse (cod, denumire) values(53,'Rage 128 ULTRA 32MB');  
insert into produse (cod, denumire) values(54,'ATX MIDI TOWER SGM52 300W Pentium 4');  
insert into produse (cod, denumire) values(55,'ATX MIDI TOWER PC230 300W');  
insert into produse (cod, denumire) values(56,'ATX MIDI TOWER PC290 300W');  
insert into produse (cod, denumire) values(57,'ATX MIDI TOWER PC250 300W');  
insert into produse (cod, denumire) values(58,'ATX MIDDLE TOWER TK6003 300W Pentium 4');  
insert into produse (cod, denumire) values(59,'ATX MIDDLE TOWER 4H48 300W Pentium 4');  
insert into produse (cod, denumire) values(60,'ATX MIDDLE TOWER 4H49 300W Pentium 4');  
insert into produse (cod, denumire) values(61,'ATX MIDDLE TOWER 88504H 300W Pentium 4');  
insert into produse (cod, denumire) values(62,'ATX MIDI TOWER TK2006 235W');  
insert into produse (cod, denumire) values(63,'ATX MIDI TOWER TK2003 235W');  
insert into produse (cod, denumire) values(64,'ATX MIDI TOWER TK2002 235W');  
insert into produse (cod, denumire) values(65,'ATX MIDI TOWER TK2001 235W');  
insert into produse (cod, denumire) values(66,'OfficeConnect Dual Speed Switch 16 Port 10/100Mbps');  
insert into produse (cod, denumire) values(67,'CARD 3C996-T, 10/100/1000 PCI-X Server');  
insert into produse (cod, denumire) values(68,'Switch SuperStack 3 3300 24 Port');  
insert into produse (cod, denumire) values(69,'Switch SuperStack 3 4400 24 Port 10/100Mbps');  
insert into produse (cod, denumire) values(70,'Switch SuperStack 3 3300TM 24 Port 10/100Mbps, Port 1000BASE-T');  
insert into produse (cod, denumire) values(71,'Switch SuperStack 3 3300MM 24 Port 10/100Mbps, Modul de stacare');  
insert into produse (cod, denumire) values(72,'Switch SuperStack 3 3300SM 24 Port 10/100Mbps, Port 1000BASE-SX');  
insert into produse (cod, denumire) values(73,'Switch SuperStack 3 3300XM 24 Port 10/100Mbps');  
insert into produse (cod, denumire) values(74,'CARD SOHO100TX');  
insert into produse (cod, denumire) values(75,'CARD 3C905C-TX-M, 10/100Mbps');  
insert into produse (cod, denumire) values(76,'CARD 3C980C-TXM, 10/100Mbps, Server');  
insert into produse (cod, denumire) values(77,'HUB 10/100Mbps, 8 Port');  
insert into produse (cod, denumire) values(78,'CARD PCMCIA 10/100 XJACK');  
insert into produse (cod, denumire) values(79,'CARD PCMCIA FM 56k + LAN 10/100, CardBus, XJACK');  
insert into produse (cod, denumire) values(80,'CARD 3C905B-FX, EtherLink 100 PCI Fiber');  
insert into produse (cod, denumire) values(81,'OfficeConnect Dual Speed Switch 8 Port10/100Mbps');  
insert into produse (cod, denumire) values(82,'HUB 10/100Mbps, 16 Port');  
insert into produse (cod, denumire) values(83,'ATA RAID Card 1200A');  
insert into produse (cod, denumire) values(84,'RAID SCSI Card 3400S, 4 canale, PCI 64 biti, 32MB Cache, KIT');  
insert into produse (cod, denumire) values(85,'RAID SCSI Card 3200S, 2 canale, PCI 64 biti, 32MB Cache, KIT');  
insert into produse (cod, denumire) values(86,'PCMCIA SCSI card, APA-1460, 16 biti');  
insert into produse (cod, denumire) values(87,'Cablu LVD cu 3 conectori, ACK-68I3-LVD, terminator activ');  
insert into produse (cod, denumire) values(88,'USBXchange, USB-to-SCSI adapter');  
insert into produse (cod, denumire) values(89,'SCSI Card 29160N, Bulk');  
insert into produse (cod, denumire) values(90,'Cablu LVD cu 5 conectori, ACK-68I5-LVD, terminator activ');  
insert into produse (cod, denumire) values(91,'RAID SCSI Card 2100S, 32MB Cache, KIT');  
insert into produse (cod, denumire) values(92,'Cablu LVD cu 9 conectori, ACK-68I9-LVD, terminator activ');  
insert into produse (cod, denumire) values(93,'PCMCIA SCSI Card APA-1480A, 32-biti');  
insert into produse (cod, denumire) values(94,'SCSI Card AVA-2904');  
insert into produse (cod, denumire) values(95,'SCSI Card AVA-2906, pt. Macintosh');  
insert into produse (cod, denumire) values(96,'SCSI Card 19160, Bulk');  
insert into produse (cod, denumire) values(97,'SCSI Card 19160, KIT');  
insert into produse (cod, denumire) values(98,'SCSI Card 29160N, KIT');  
insert into produse (cod, denumire) values(99,'SCSI Card 39160, KIT');  
insert into produse (cod, denumire) values(100,'ATA RAID Card 2400A, 32 MB Cache');  
insert into produse (cod, denumire) values(101,'SCSI Card 39160, Bulk');  
insert into produse (cod, denumire) values(102,'SCSI Card PowerDomain 29160N, pt. Macintosh');  
insert into produse (cod, denumire) values(103,'Duron 800 MHz');  
insert into produse (cod, denumire) values(104,'Duron 850 MHz');  
insert into produse (cod, denumire) values(105,'Duron 900 MHz');  
insert into produse (cod, denumire) values(106,'Duron 1000 MHz');  
insert into produse (cod, denumire) values(107,'Duron 1100 MHz');  
insert into produse (cod, denumire) values(108,'Athlon 1.2 GHz FSB266');  
insert into produse (cod, denumire) values(109,'Athlon 1.4 GHz FSB266');  
insert into produse (cod, denumire) values(110,'Athlon XP 1800+ FSB266');  
insert into produse (cod, denumire) values(111,'Athlon XP 1500+ FSB266');  
insert into produse (cod, denumire) values(112,'Athlon XP 1600+ FSB266');  
insert into produse (cod, denumire) values(113,'Duron 950 MHz');  
insert into produse (cod, denumire) values(114,'Radeon 7500 64DDR, chip Radeon 7500, DAC 350MHz, AGP 4X, multi-afisare');  
insert into produse (cod, denumire) values(115,'Radeon 8500 64DDR, chip Radeon 8500, DAC 400MHz, AGP 4X, multi-afisare');  
insert into produse (cod, denumire) values(116,'All-In-Wonder Radeon 32MB DDR, chip Radeon, DAC 350MHz, PAL B/G + D/K, AGP 4X, intrare/iesire audio+vi deo, retail');  
insert into produse (cod, denumire) values(117,'DV Wonder, interfata FireWire, 3 porturi externe');  
insert into produse (cod, denumire) values(118,'Xpert 2000 PRO 16MB SGRAM, chip Rage 128 PRO, DAC 300MHz, AGP 4X, bulk');  
insert into produse (cod, denumire) values(119,'Radeon VE 32MB DDR, chip Radeon VE, DAC 300MHz, AGP 4X, iesiri DVI + video, multi-afisare, bulk');  
insert into produse (cod, denumire) values(120,'Rage Fury PRO VIVO 32MB SGRAM, chip Rage 128 PRO GL, DAC 300MHz, AGP 4X, intrari/iesiri video, bulk');  
insert into produse (cod, denumire) values(121,'Xpert 2000 PRO 32MB SGRAM, chip Rage 128 PRO, DAC 300MHz, AGP 4X, bulk');  
insert into produse (cod, denumire) values(122,'TV Wonder Light, PCI, audio mono, PAL B/G + D/K, bulk');  
insert into produse (cod, denumire) values(123,'TV Wonder, PCI, audio stereo, PAL B/G + D/K, bulk');  
insert into produse (cod, denumire) values(124,'TV Wonder retail, PCI, audio stereo, PAL B/G + D/K, retail');  
insert into produse (cod, denumire) values(125,'Radeon 32MB SDR, chip Radeon, DAC 350MHz, AGP 4X, bulk');  
insert into produse (cod, denumire) values(126,'Multipass C70, A4, printer, scaner, copiator, fax, 720x360 dpi');  
insert into produse (cod, denumire) values(127,'CANON FAX B155, A4, 360x360dpi');  
insert into produse (cod, denumire) values(128,'CANON BJC-1000, A4, 720x360dpi');  
insert into produse (cod, denumire) values(129,'CANON BJC-2100, A4, 720x360dpi');  
insert into produse (cod, denumire) values(130,'CANON BJC-S400, A4, 1440x720dpi');  
insert into produse (cod, denumire) values(131,'CANON BJC-S450, A4, 1440x720dpi');  
insert into produse (cod, denumire) values(132,'CANON LBP 810, A4, 600dpi, 2MB');  
insert into produse (cod, denumire) values(133,'Armada Evo N150 P800/128MB/15GB/14.1"TFT/DVD8X/audio/FaxModem/LAN/WinME');  
insert into produse (cod, denumire) values(134,'Presario 2701EA P1200 M/512MB/30GB/15"TFT/DVD8X/audio/FaxModem/LAN/WinXP Home');  
insert into produse (cod, denumire) values(135,'Juke Box, Digital Audio Player, 6GB, USB');  
insert into produse (cod, denumire) values(136,'3D Blaster GeForce2 Titanium, 64MB, chip GeForce2Ti, TV-Out');  
insert into produse (cod, denumire) values(137,'Sound Blaster AUDIGY Platinum EX, 5.1');  
insert into produse (cod, denumire) values(138,'Sound Blaster AUDIGY Platinum, 5.1');  
insert into produse (cod, denumire) values(139,'Sound Blaster AUDIGY Player, 5.1');  
insert into produse (cod, denumire) values(140,'Sound Blaster Audigy Player bulk, 5.1');  
insert into produse (cod, denumire) values(141,'Juke Box, Digital Audio Player, 20GB, USB');  
insert into produse (cod, denumire) values(142,'FPS1600, 4 Point surround, Subwoofer');  
insert into produse (cod, denumire) values(143,'Sound Works Digital, Subwoofer');  
insert into produse (cod, denumire) values(144,'DTT2200, Desktop Theatre 5.1, Subwoofer');  
insert into produse (cod, denumire) values(145,'Inspire 5.1 5300, subwoofer');  
insert into produse (cod, denumire) values(146,'DTT3500, PlayWorks 5.1, Subwoofer');  
insert into produse (cod, denumire) values(147,'Inspire 5700, subwoofer');  
insert into produse (cod, denumire) values(148,'Cablu 2 Joystick');  
insert into produse (cod, denumire) values(149,'KIT Sound Blaster LIVE Player 5.1 + DTT 2200');  
insert into produse (cod, denumire) values(150,'WebCam 5, USB');  
insert into produse (cod, denumire) values(151,'Video Blaster Web PC-Cam 300, USB');  
insert into produse (cod, denumire) values(152,'CSW320, Subwoofer');  
insert into produse (cod, denumire) values(153,'17" PR711F FD Trinitron, .24dp, OSD, 95kHz, TCO99, USB HUB');  
insert into produse (cod, denumire) values(154,'15" VL500, OSD, 70kHz');  
insert into produse (cod, denumire) values(155,'17" VL700, OSD, 70kHz');  
insert into produse (cod, denumire) values(156,'17" VL710T, .26dp, OSD, 95kHz, TCO95');  
insert into produse (cod, denumire) values(157,'17" EX710F, .25dp, OSD, 97kHz, TCO99, Flat');  
insert into produse (cod, denumire) values(158,'17" PR705F FD Trinitron, .24dp, OSD, 85kHz, TCO99');  
insert into produse (cod, denumire) values(159,'19" VL950T, .26dp, OSD, 95kHz, TCO95');  
insert into produse (cod, denumire) values(160,'CD ROM 56x, interna, IDE, bulk');  
insert into produse (cod, denumire) values(161,'19" VL950SLT, .26dp, OSD, 95kHz, high contrast, TCO95, short length');  
insert into produse (cod, denumire) values(162,'17" EX700F, .25dp, OSD, 72kHz, TCO99, Flat');  
insert into produse (cod, denumire) values(163,'19" EX950F, .25dp, OSD, 97kHz, TCO99, Flat');  
insert into produse (cod, denumire) values(164,'19" PR960F FD Trinitron, .24dp, OSD, 110kHz, TCO99, USB HUB, BNC');  
insert into produse (cod, denumire) values(165,'21" VL1300 FD Trinitron, .26dp, OSD, 115KHz, TCO95');  
insert into produse (cod, denumire) values(166,'21" PR1400F FD Trinitron, .24dp, OSD, 125kHz, TCO99, USB HUB, BNC');  
insert into produse (cod, denumire) values(167,'LCD 15.1" TFT, PV505S, TCO95, USB');  
insert into produse (cod, denumire) values(168,'LCD 15.1" TFT, PV520S, TCO95, USB, PIVOT, SILVER');  
insert into produse (cod, denumire) values(169,'17" FD Trinitron PR711FL, 0.25dp, OSD, 95KHz, TCO99');  
insert into produse (cod, denumire) values(170,'CD-ROM 52x, interna, IDE, retail');  
insert into produse (cod, denumire) values(171,'Socket 370, CM33-EC, VIA PLE133, FSB133, SDRAM, mATX, UDMA 100, audio, video');  
insert into produse (cod, denumire) values(172,'Socket A, AK75-EC, VIA KT133A, FSB266, SDRAM, ATX, UDMA 100, audio');  
insert into produse (cod, denumire) values(173,'Socket 423, WT70-EC, Intel 850, FSB400, RDRAM, ATX, UDMA 100, audio');  
insert into produse (cod, denumire) values(174,'Socket 423, WB72-SC, Intel 845, FSB400, SDRAM, ATX, UDMA 100, audio');  
insert into produse (cod, denumire) values(175,'Set carcase CD Double, 5 buc. (ED64030)');  
insert into produse (cod, denumire) values(176,'Cartus CANON BJC 2000/4000/5000 (BCI-21c) (ED21004) - color');  
insert into produse (cod, denumire) values(177,'Copy Holder A4 (ED64001)');  
insert into produse (cod, denumire) values(178,'Stand Monitor (ED64003)');  
insert into produse (cod, denumire) values(179,'Brat Monitor, max. 25Kg (ED64005)');  
insert into produse (cod, denumire) values(180,'Cablu de tensiune Y, intern, 5.25 (ED84041)');  
insert into produse (cod, denumire) values(181,'Cartus CANON BJC 3000/6000 (BCI-3c) (ED21006) - cyan');  
insert into produse (cod, denumire) values(182,'Power Cleaner, spray (ED63004)');  
insert into produse (cod, denumire) values(183,'Cartus CANON BJC 3000/6000 (BCI-3m) (ED21007) - magenta');  
insert into produse (cod, denumire) values(184,'CD Mobile Box, pt. 10CD-uri (ED62010)');  
insert into produse (cod, denumire) values(185,'Cartus CANON BJC 3000/6000 (BCI-3y) (ED21008) - yellow');  
insert into produse (cod, denumire) values(186,'Set carcase CD Rainbow, 6 buc. (ED64033)');  
insert into produse (cod, denumire) values(187,'Cartus CANON BJC 3000/6000 (BCI-3bk) (ED21005) - negru');  
insert into produse (cod, denumire) values(188,'Set carcase CD, 5 buc. (ED64031)');  
insert into produse (cod, denumire) values(189,'Husa Monitor 15"-17" (ED64060)');  
insert into produse (cod, denumire) values(190,'Mouse Pad (ED64010)');  
insert into produse (cod, denumire) values(191,'Husa pt. tastatura (ED64062)');  
insert into produse (cod, denumire) values(192,'Geanta Notebook "Expandable" (ED64055)');  
insert into produse (cod, denumire) values(193,'Geanta Notebook "Executive" (ED64054)');  
insert into produse (cod, denumire) values(194,'Geanta Notebook "Active" (ED64053)');  
insert into produse (cod, denumire) values(195,'Geanta Notebook "College" (ED64052)');  
insert into produse (cod, denumire) values(196,'Geanta Notebook "Bussines" (ED64051)');  
insert into produse (cod, denumire) values(197,'Cartus CANON BJC 2000/4000/5000 (BCI-21bk) (ED21003) - negru');  
insert into produse (cod, denumire) values(198,'CD Cleaning Tissues, 100 buc. (ED63011)');  
insert into produse (cod, denumire) values(199,'Palm Pad cu gel (ED64022)');  
insert into produse (cod, denumire) values(200,'Screen Cleaner, solutie 250 ml (ED63005)');  
insert into produse (cod, denumire) values(201,'Mouse Pad - Picture Pad I (ED64011)');  
insert into produse (cod, denumire) values(202,'Surface Cleaner, 100 servetele (ED63001)');  
insert into produse (cod, denumire) values(203,'Mouse Pad - Picture Pad II (ED64012)');  
insert into produse (cod, denumire) values(204,'Husa Monitor 17"-19" (ED64061)');  
insert into produse (cod, denumire) values(205,'CD Drive Cleaner (ED63010)');  
insert into produse (cod, denumire) values(206,'Hartie Photo Glossy Premium, A4, 240g, 10 coli (ED41002)');  
insert into produse (cod, denumire) values(207,'Geanta Notebook "Standard" (ED64050)');  
insert into produse (cod, denumire) values(208,'Cablu Extensie PS/2, 1.8m (ED84021)');  
insert into produse (cod, denumire) values(209,'Casti mono cu microfon (ED83021)');  
insert into produse (cod, denumire) values(210,'Casti stereo w/Control Volum (ED83020)');  
insert into produse (cod, denumire) values(211,'Microfon PC (ED83011)');  
insert into produse (cod, denumire) values(212,'Microfon Clip (ED83010)');  
insert into produse (cod, denumire) values(213,'Cablu audio stereo, jack, extensie (ED84033)');  
insert into produse (cod, denumire) values(214,'Cablu Extensie VGA, 1.8m (ED84020)');  
insert into produse (cod, denumire) values(215,'ED DVD WALLET, 16 CD-uri (ED62015)');  
insert into produse (cod, denumire) values(216,'Cablu Extensie AT, 1.8m (ED84022)');  
insert into produse (cod, denumire) values(217,'Cablu Tensiune PC (ED84060)');  
insert into produse (cod, denumire) values(218,'Cablu USB A/A, 1.8m (ED84051)');  
insert into produse (cod, denumire) values(219,'Cablu USB A/B, 1.8m (ED84052)');  
insert into produse (cod, denumire) values(220,'Cablu IDE, UDMA/33 (ED84040)');  
insert into produse (cod, denumire) values(221,'Cablu paralel pt. imprimanta, 1.8m (ED84010)');  
insert into produse (cod, denumire) values(222,'Cablu serial pt. switch de imprimante, 25 pini, 1.8m (ED84064)');  
insert into produse (cod, denumire) values(223,'Cablu USB A/B, 3m (ED84053)');  
insert into produse (cod, denumire) values(224,'Cablu Null Modem, 25 pini (M) - 25 pini (M), 1.8m (ED84062)');  
insert into produse (cod, denumire) values(225,'Cablu paralel pt. imprimanta, bulk, 1.8m (ED84014)');  
insert into produse (cod, denumire) values(226,'Disk Box, pt. 50 dischete (ED62001)');  
insert into produse (cod, denumire) values(227,'Cablu paralel pt. imprimanta, 3m (ED84011)');  
insert into produse (cod, denumire) values(228,'Hartie Photo Glossy, A4, 170g, 25 coli (ED41003)');  
insert into produse (cod, denumire) values(229,'Cartus HP DJ 690C (51629A) (ED23003) - negru');  
insert into produse (cod, denumire) values(230,'Cartus HP DJ 800 (51645A) (ED23005) negru');  
insert into produse (cod, denumire) values(231,'Cartus HP DJ 690C (51649A) (ED23004) - color');  
insert into produse (cod, denumire) values(232,'Set carcase DVD, 3 buc. (ED64040)');  
insert into produse (cod, denumire) values(233,'Adaptor Tastatura, PS2->AT (ED84003)');  
insert into produse (cod, denumire) values(234,'Casti stereo cu microfon (ED83022)');  
insert into produse (cod, denumire) values(235,'CD Organizer, pt. 16 CD-uri (ED62032)');  
insert into produse (cod, denumire) values(236,'Cablu audio stereo, jack-jack (ED84031)');  
insert into produse (cod, denumire) values(237,'Cablu paralel pt. imprimanta, Half Pitch, bidir., 1.8m (ED84013)');  
insert into produse (cod, denumire) values(238,'Cablu paralel pt. imprimanta, bidir., 1.8m (ED84012)');  
insert into produse (cod, denumire) values(239,'CD/MD/ZIP Disk Flipper pt. 14 buc. (ED62031)');  
insert into produse (cod, denumire) values(240,'CD Porty Box, pt. 16CD/DVD-uri (ED62014)');  
insert into produse (cod, denumire) values(241,'Cablu de tensiune Y, intern, 5.25"+3.5" (ED84042)');  
insert into produse (cod, denumire) values(242,'Cablu Tensiune PC, extensie, 1.8m (ED84061)');  
insert into produse (cod, denumire) values(243,'Hartie Photo Glossy Double Side, A4, 170g, 10 coli (ED41001)');  
insert into produse (cod, denumire) values(244,'CD Module Tower, pt. 20 CD-uri (ED 62030)');  
insert into produse (cod, denumire) values(245,'ED CD RACK 20 StyleLine (ED62050)');  
insert into produse (cod, denumire) values(246,'ED DVD/CD TOWER SL (ED62053)');  
insert into produse (cod, denumire) values(247,'CD Wallet, pt. 20CD-uri (ED62012)');  
insert into produse (cod, denumire) values(248,'Disk Box, pt. 100 dischete (ED62002)');  
insert into produse (cod, denumire) values(249,'CD Box, pt. 26/80 CD-uri (ED62020)');  
insert into produse (cod, denumire) values(250,'CD Box, pt. 30/120 CD-uri (ED62021)');  
insert into produse (cod, denumire) values(251,'ED CD SMART BOX StyleLine (ED62051)');  
insert into produse (cod, denumire) values(252,'ED CD MEDIA STATION SL (ED62052)');  
insert into produse (cod, denumire) values(253,'Adaptor Tastatura, AT->PS2 (ED84002)');  
insert into produse (cod, denumire) values(254,'Adaptor Serial, 9 pini (M) - 25 pini (F) (ED84001)');  
insert into produse (cod, denumire) values(255,'Hub USB extern, 4 porturi (ED85010)');  
insert into produse (cod, denumire) values(256,'ED PC SERVICE SET PRO (ED64071)');  
insert into produse (cod, denumire) values(257,'CD ROTA Jukebox, pt. 40 CD/DVD-uri (ED62023)');  
insert into produse (cod, denumire) values(258,'PC Service Set (ED64070)');  
insert into produse (cod, denumire) values(259,'Switch manual pt. imprimante, 2 porturi (ED85001)');  
insert into produse (cod, denumire) values(260,'CD Jukebox, pt. 100 CD/DVD-uri (ED62022)');  
insert into produse (cod, denumire) values(261,'CD Tower, pt. 20 CD-uri (ED62034)');  
insert into produse (cod, denumire) values(262,'Stylus Photo 1290, A3+, 2880x720dpi, imprimare cu 6 culori');  
insert into produse (cod, denumire) values(263,'Stylus Photo 810, A4, 2880x720dpi, imprimare cu 6 culori');  
insert into produse (cod, denumire) values(264,'Stylus C70, A4, 2880x720dpi, cartuse separate pe culori');  
insert into produse (cod, denumire) values(265,'Stylus Photo 890, A4, 2880x720dpi, imprimare cu 6 culori');  
insert into produse (cod, denumire) values(266,'Stylus C80, A4, 2880x720dpi, cartuse separate pe culori');  
insert into produse (cod, denumire) values(267,'Stylus Color 1160, A3, 1440x720');  
insert into produse (cod, denumire) values(268,'Stylus Color 1520, A2, 1440x720dpi');  
insert into produse (cod, denumire) values(269,'LQ 300+, A4, 24 Pini, 300 cps, opt. color');  
insert into produse (cod, denumire) values(270,'FX-880, 9 Pini, A4, 455cps');  
insert into produse (cod, denumire) values(271,'FX-1180, A3, 9 ace, 455cps');  
insert into produse (cod, denumire) values(272,'Stylus C60, A4, 2880x720dpi');  
insert into produse (cod, denumire) values(273,'FX 2180, A3, 18 ace, 500cps');  
insert into produse (cod, denumire) values(274,'LX 300+, A4, 9 Ace, 264 cps, opt. color');  
insert into produse (cod, denumire) values(275,'LQ 2180, A3, 24 Ace, 480cps');  
insert into produse (cod, denumire) values(276,'LQ 2080, A3, 24 Ace, 400cps');  
insert into produse (cod, denumire) values(277,'Stylus C40UX, A4, 1440x720dpi');  
insert into produse (cod, denumire) values(278,'RIBON LX-1050/ FX-11XX ( 8755 )');  
insert into produse (cod, denumire) values(279,'RIBON FX/LX A4 ( 8750 )');  
insert into produse (cod, denumire) values(280,'Hartie foto glossy, A4, 20 coli');  
insert into produse (cod, denumire) values(281,'Hartie foto, A4, 20 coli');  
insert into produse (cod, denumire) values(282,'RIBON LQ A4 ( 7753 )');  
insert into produse (cod, denumire) values(283,'Hartie foto mata, A4, 100 coli');  
insert into produse (cod, denumire) values(284,'RIBON FX 21xx/LQ 21xx ( S015086 )');  
insert into produse (cod, denumire) values(285,'RIBON DFX-5000/8000 ( 8766 )');  
insert into produse (cod, denumire) values(286,'LX-1170, A3, 9 Ace, 337cps');  
insert into produse (cod, denumire) values(287,'Navigator P866CD P866/128MB/20GB/14,1"TFT/CD24X/audio/FaxModem/LAN/WinME');  
insert into produse (cod, denumire) values(288,'Maestro V1000');  
insert into produse (cod, denumire) values(289,'Diablo 6666 PRO');  
insert into produse (cod, denumire) values(290,'Maestro V300');  
insert into produse (cod, denumire) values(291,'Diablo 6666 G');  
insert into produse (cod, denumire) values(292,'Navigator P1000W P1000/256MB/30GB/14,1"TFT/CDRW 8x4x24x/audio/FaxModem/LAN/WinME');  
insert into produse (cod, denumire) values(293,'Navigator P1000DVD P1000/256MB/20GB/14,1"TFT/DVD8X/audio/FaxModem/LAN/WinME');  
insert into produse (cod, denumire) values(294,'Assistant 2000');  
insert into produse (cod, denumire) values(295,'Conecta K');  
insert into produse (cod, denumire) values(296,'Diablo 666A');  
insert into produse (cod, denumire) values(297,'Genius M1000');  
insert into produse (cod, denumire) values(298,'Genius A1600+');  
insert into produse (cod, denumire) values(299,'Atlas S3000');  
insert into produse (cod, denumire) values(300,'Conecta I');  
insert into produse (cod, denumire) values(301,'Assistant Plus');  
insert into produse (cod, denumire) values(302,'Genius D1000');  
insert into produse (cod, denumire) values(303,'Maestro V2000');  
insert into produse (cod, denumire) values(304,'Diablo 666I');  
insert into produse (cod, denumire) values(305,'Atlas S2000');  
insert into produse (cod, denumire) values(306,'Navigator C850CD C850/128MB/10GB/14,1"TFT/CD24X/audio/FaxModem/LAN/WinME');  
insert into produse (cod, denumire) values(307,'FLAMINGO GENIUS P4 1500');  
insert into produse (cod, denumire) values(308,'KIT ATX MINI TOWER Venus 200W');  
insert into produse (cod, denumire) values(309,'Speakers SW-4.1');  
insert into produse (cod, denumire) values(310,'Speakers SW-G106');  
insert into produse (cod, denumire) values(311,'Genius 56k, intern, PCI');  
insert into produse (cod, denumire) values(312,'Genius 56k extern USB');  
insert into produse (cod, denumire) values(313,'Speakers SW-2.1 SLIM');  
insert into produse (cod, denumire) values(314,'Speakers G16, PMPO 320W');  
insert into produse (cod, denumire) values(315,'Speakers SP-M2 Slim, PMPO 150W');  
insert into produse (cod, denumire) values(316,'Speakers SP-205B, PMPO 120W');  
insert into produse (cod, denumire) values(317,'Speakers G10, PMPO 200W');  
insert into produse (cod, denumire) values(318,'Speakers G06, PMPO 120W');  
insert into produse (cod, denumire) values(319,'Speakers SW-5.1');  
insert into produse (cod, denumire) values(320,'Scaner ColorPage VIVID 4');  
insert into produse (cod, denumire) values(321,'Speakers M06U, USB');  
insert into produse (cod, denumire) values(322,'Scaner ColorPage HR6A, ADF');  
insert into produse (cod, denumire) values(323,'Scaner ColorPage VIVID 3X USB');  
insert into produse (cod, denumire) values(324,'Microfon MIC-01C');  
insert into produse (cod, denumire) values(325,'Scaner ColorPage VIVID 3X');  
insert into produse (cod, denumire) values(326,'Scaner ColorPage VIVID 3XE');  
insert into produse (cod, denumire) values(327,'HUB 100BASE-TX, GF4080, 8 port');  
insert into produse (cod, denumire) values(328,'Keyboard KB-18M, multimedia , PS/2');  
insert into produse (cod, denumire) values(329,'Keyboard KB-18M, multimedia');  
insert into produse (cod, denumire) values(330,'Keyboard KB-10, wrist pad, PS/2');  
insert into produse (cod, denumire) values(331,'HUB 10BASE-T, GH4160, 16 port');  
insert into produse (cod, denumire) values(332,'HUB 10BASE-T, GH4080, 8 port');  
insert into produse (cod, denumire) values(333,'HUB USB, Genius, 4 port');  
insert into produse (cod, denumire) values(334,'Keyboard KB-10, wrist pad');  
insert into produse (cod, denumire) values(335,'Keyboard KB-06');  
insert into produse (cod, denumire) values(336,'Scaner ColorPage HR7X, transparenta');  
insert into produse (cod, denumire) values(337,'PCMCIA Card, MF3000, 100Mbps');  
insert into produse (cod, denumire) values(338,'Keyboard KB-06, PS/2');  
insert into produse (cod, denumire) values(339,'Joystick MaxFighter Digital F-31D');  
insert into produse (cod, denumire) values(340,'Headphones w. MIC HS-02, Genius');  
insert into produse (cod, denumire) values(341,'Scaner ColorPage HR6, transparenta');  
insert into produse (cod, denumire) values(342,'Mouse Netscroll +, Serial');  
insert into produse (cod, denumire) values(343,'Volan Speed Wheel, Force Feedback, pedale, USB');  
insert into produse (cod, denumire) values(344,'Keyboard KB-16M, multimedia , PS/2, Cordless');  
insert into produse (cod, denumire) values(345,'KIT KB + Mouse Cordless, Twin Touch');  
insert into produse (cod, denumire) values(346,'MOUSE NET SCROLL OPT USB');  
insert into produse (cod, denumire) values(347,'Mouse NetScroll Optical, PS/2');  
insert into produse (cod, denumire) values(348,'Mouse NetScroll+ Eye, optic, PS/2');  
insert into produse (cod, denumire) values(349,'Mouse NetScroll+ Eye, optic, USB');  
insert into produse (cod, denumire) values(350,'Trackball KidsBall');  
insert into produse (cod, denumire) values(351,'Easy Trak');  
insert into produse (cod, denumire) values(352,'Net Scroll +, USB');  
insert into produse (cod, denumire) values(353,'Joystick MaxFighter F-33D, Force Feedback, USB');  
insert into produse (cod, denumire) values(354,'Tableta grafica EasyPen');  
insert into produse (cod, denumire) values(355,'New Sketch 1812 HR');  
insert into produse (cod, denumire) values(356,'Net Scroll +, PS/2');  
insert into produse (cod, denumire) values(357,'Easy Mouse +, PS/2');  
insert into produse (cod, denumire) values(358,'Easy Mouse +');  
insert into produse (cod, denumire) values(359,'Easy Mouse PRO, PS/2');  
insert into produse (cod, denumire) values(360,'Easy Mouse, PS/2');  
insert into produse (cod, denumire) values(361,'Easy Mouse');  
insert into produse (cod, denumire) values(362,'Tableta grafica NewSketch 1212HRIII');  
insert into produse (cod, denumire) values(363,'ePen');  
insert into produse (cod, denumire) values(364,'KIT ATX MIDI TOWER Hercules 235W');  
insert into produse (cod, denumire) values(365,'KIT ATX MIDI TOWER Venus 250W P4');  
insert into produse (cod, denumire) values(366,'Easy Mouse +, USB');  
insert into produse (cod, denumire) values(367,'Sound Maker 32X, Crystal CS4281 chip, PCI, Genius');  
insert into produse (cod, denumire) values(368,'Joystick Flight2000 F-22X');  
insert into produse (cod, denumire) values(369,'Gamepad MaxFire G-07, USB');  
insert into produse (cod, denumire) values(370,'Gamepad MaxFire G-08');  
insert into produse (cod, denumire) values(371,'Mouse NetScroll+ Notebook Eye, optic, USB+PS/2');  
insert into produse (cod, denumire) values(372,'KIT ATX MIDI TOWER Venus Value 235W');  
insert into produse (cod, denumire) values(373,'Sound Maker LIVE 5.1, Forte Media FM802AU, PCI, Genius');  
insert into produse (cod, denumire) values(374,'Consola PowerStation');  
insert into produse (cod, denumire) values(375,'Sound Maker 128 Value, Crystal CS4614 chip, PCI, Genius');  
insert into produse (cod, denumire) values(376,'GF100TXR PCI Card, UTP, 10/100Mbps');  
insert into produse (cod, denumire) values(377,'10/100 LAN/USB Adapter');  
insert into produse (cod, denumire) values(378,'KIT ATX MIDI TOWER Mars 200W');  
insert into produse (cod, denumire) values(379,'Microfon MIC-01A');  
insert into produse (cod, denumire) values(380,'Volan Speed Wheel Formula, pedale, schimbator');  
insert into produse (cod, denumire) values(381,'New Scroll Wireless');  
insert into produse (cod, denumire) values(382,'Joystick Flight2000 F-23, USB');  
insert into produse (cod, denumire) values(383,'Gamepad MaxFire G-09D, Vibration Control');  
insert into produse (cod, denumire) values(384,'Sound Maker LIVE, Forte Media FM801, PCI, Genius');  
insert into produse (cod, denumire) values(385,'17" 710DT, .26dp, 96kHz, TCO99, Dynaflat');  
insert into produse (cod, denumire) values(386,'21" 2100A, .25dp, 107kHz, TCO99');  
insert into produse (cod, denumire) values(387,'17" 720CA, .27dp, 72kHz, TCO99');  
insert into produse (cod, denumire) values(388,'19" 900PT, .26dp, 96kHz, TCO99');  
insert into produse (cod, denumire) values(389,'17" 710PT, .26dp, 96kHz, TCO99');  
insert into produse (cod, denumire) values(390,'LCD 17.0" TFT, 700F, TCO99');  
insert into produse (cod, denumire) values(391,'19" 920DT, .25dp, 96kHz, TCO99, Dynaflat');  
insert into produse (cod, denumire) values(392,'DeskJet 990cxi, A4, 2400x1200dpi, 8MB, duplex');  
insert into produse (cod, denumire) values(393,'DeskJet 1125C, A3+, 600x1200dpi, 4MB');  
insert into produse (cod, denumire) values(394,'DeskJet 350CBi, A4, 600dpi, 512KB, pt. notebook, IrDA');  
insert into produse (cod, denumire) values(395,'DeskJet 1220C, A3+, 2400x1200dpi, 8MB');  
insert into produse (cod, denumire) values(396,'Business InkJet 2200, A4, 2400x1200dpi, 8MB, cartuse separate pe culori');  
insert into produse (cod, denumire) values(397,'Business InkJet 2250, A4, 2400x1200dpi, 24MB, PostScript 2, cartuse separate pe culori');  
insert into produse (cod, denumire) values(398,'DesignJet 430, A1, monocrom, 600dpi, 4MB');  
insert into produse (cod, denumire) values(399,'DesignJet 430, A0, monocrom, 600dpi, 4MB');  
insert into produse (cod, denumire) values(400,'DesignJet 500, A0+, color, 1200x600dpi, 16MB');  
insert into produse (cod, denumire) values(401,'DeskJet 980Cxi, A4, 2400x1200dpi, 8MB, duplex');  
insert into produse (cod, denumire) values(402,'Toner negru LJ 1200/1220 (C7115A)');  
insert into produse (cod, denumire) values(403,'LaserJet 1000, A4, 300 dpi, 1MB');  
insert into produse (cod, denumire) values(404,'LaserJet 2200D, A4, 1200dpi, 8MB, Postscript 2, duplex');  
insert into produse (cod, denumire) values(405,'HP Black Cartridge DJ840');  
insert into produse (cod, denumire) values(406,'HP Color Cartridge DJ1120C');  
insert into produse (cod, denumire) values(407,'HP Color Cartridge DJ600 series');  
insert into produse (cod, denumire) values(408,'HP Black Cartridge DJ400/500 series');  
insert into produse (cod, denumire) values(409,'HP Black Cartridge DJ800/1600');  
insert into produse (cod, denumire) values(410,'HP Black Cartridge DJ600 series');  
insert into produse (cod, denumire) values(411,'HP Cartridge for DJ 2200 C, M, Y ( C4836AE)');  
insert into produse (cod, denumire) values(412,'Toner for LJ4(M)L, 4(M)P ( 92274A )');  
insert into produse (cod, denumire) values(413,'HP Color Cartridge DJ840');  
insert into produse (cod, denumire) values(414,'HP Cyan Cartridge DJ 2000/2500 (C4841AE)');  
insert into produse (cod, denumire) values(415,'HP Black Cartridge DJ610');  
insert into produse (cod, denumire) values(416,'HP PHOTO PAPER ( C1847A)');  
insert into produse (cod, denumire) values(417,'HP PREM. PHOTO PAPER A4 ( C6040A )');  
insert into produse (cod, denumire) values(418,'OmniBook XE3 C850/128MB/10GB/14,1"TFT/CD24X/audio/FaxModem/WinME');  
insert into produse (cod, denumire) values(419,'OmniBook XE3 P1000/128MB/20GB/15"TFT/DVD8X/audio/FaxModem/LAN/Win98');  
insert into produse (cod, denumire) values(420,'HP Toner Cartridge LJ2100');  
insert into produse (cod, denumire) values(421,'HP Black Cartridge for DJ350 ( C6628A)');  
insert into produse (cod, denumire) values(422,'LaserJet 2200DN, A4, 1200dpi, 8MB, Postscript 2, duplex, network');  
insert into produse (cod, denumire) values(423,'Photosmart P100, 10x15cm, 2400x1200dpi');  
insert into produse (cod, denumire) values(424,'DeskJet 940C, A4, 2400x1200dpi, 2MB');  
insert into produse (cod, denumire) values(425,'DeskJet 930C, A4, 2400x1200dpi, 4MB');  
insert into produse (cod, denumire) values(426,'DeskJet 920C, A4, 2400x1200dpi, 2MB');  
insert into produse (cod, denumire) values(427,'DeskJet 845C, A4, 600x1200dpi, 2MB');  
insert into produse (cod, denumire) values(428,'DeskJet 656C, A4, 600dpi, 512Kb');  
insert into produse (cod, denumire) values(429,'HP Color Cartridge DJ9XX, DJ1220C');  
insert into produse (cod, denumire) values(430,'HP Toner Cartridge 4/4M');  
insert into produse (cod, denumire) values(431,'HP Black Cartridge DJ 2000/2500/22XX (C4844A)');  
insert into produse (cod, denumire) values(432,'HP Toner Cartridge 5P/5MP');  
insert into produse (cod, denumire) values(433,'LaserJet 2200DT, A4, 1200dpi, 8MB, Postscript 2, duplex, tava suplimentara');  
insert into produse (cod, denumire) values(434,'HP Toner Cartridge 5L');  
insert into produse (cod, denumire) values(435,'HP Toner Cartridge LJ1100');  
insert into produse (cod, denumire) values(436,'HP PREM. PHOTO PAPER A3 ( C6059A )');  
insert into produse (cod, denumire) values(549,'Atlas 10K III, 36.7GB, UltraWide SCSI, 10000rpm');  
insert into produse (cod, denumire) values(550,'Atlas 10K III, 18.4GB, UltraWide SCSI, 10000rpm');  
insert into produse (cod, denumire) values(551,'Atlas V, 18.4GB, SCSI Ultra 160, 7200rpm');  
insert into produse (cod, denumire) values(552,'Atlas V, 9.1GB, SCSI Ultra Wide, 7200rpm');  
insert into produse (cod, denumire) values(553,'20.0GB 541DX, RPM 5400, UATA/100');  
insert into produse (cod, denumire) values(554,'MS7220 (ARGUS) - kb');  
insert into produse (cod, denumire) values(555,'MK6130 - serial');  
insert into produse (cod, denumire) values(556,'MS6720 - serial');  
insert into produse (cod, denumire) values(557,'MK6130 - kb');  
insert into produse (cod, denumire) values(558,'MS860i - kb');  
insert into produse (cod, denumire) values(559,'MS7120 (Orbit) - serial');  
insert into produse (cod, denumire) values(560,'MS7120 (Orbit) - kb');  
insert into produse (cod, denumire) values(561,'MS9520 (Voyager) - serial');  
insert into produse (cod, denumire) values(562,'MS 860i - serial');  
insert into produse (cod, denumire) values(563,'MS6720 - kb');  
insert into produse (cod, denumire) values(564,'MS9540CG (Voyager) - kb (tehnologie "Codegate")');  
insert into produse (cod, denumire) values(565,'MS9540CG (Voyager) - serial (tehnologie "Codegate")');  
insert into produse (cod, denumire) values(566,'ScanPal2 CE');  
insert into produse (cod, denumire) values(567,'MS9520 (Voyager) - kb');  
insert into produse (cod, denumire) values(568,'MS700i - kb');  
insert into produse (cod, denumire) values(569,'MS700i - serial');  
insert into produse (cod, denumire) values(570,'MS720I - serial');  
insert into produse (cod, denumire) values(571,'ScanPal 2 LE');  
insert into produse (cod, denumire) values(572,'Internet Keybrd Win9x (PS/2) English Hdwr CD Euro');  
insert into produse (cod, denumire) values(573,'Intellimouse Explorer PS2/USB');  
insert into produse (cod, denumire) values(574,'Volan SideWinder Force Feedback Wheel, pedale, USB');  
insert into produse (cod, denumire) values(575,'Joystick SideWinder Force Feedback 2, Twist Handle, USB');  
insert into produse (cod, denumire) values(576,'Game Controller SideWinder Dual Strike, USB');  
insert into produse (cod, denumire) values(577,'Intellimouse Optical PS2/USB');  
insert into produse (cod, denumire) values(578,'IntelliMse 3.0 (Ser+PS/2)');  
insert into produse (cod, denumire) values(579,'Gamepad SideWinder Freestyle Pro, USB');  
insert into produse (cod, denumire) values(580,'GeForce2 MX 400 32MB, GeForce2 MX 400, 32MB SDRAM');  
insert into produse (cod, denumire) values(581,'GeForce2 MX 400 64MB TV-Out, GeForce2 MX 400, 64MB SDRAM, iesire video');  
insert into produse (cod, denumire) values(582,'GeForce2 MX 400 32MB VIVO, GeForce2 MX 400, 32MB SDRAM, iesire/intrare video');  
insert into produse (cod, denumire) values(583,'GeForce2 Ti 64MB DDR VIVO, GeForce2 Ti, 64MB DDR, VIVO');  
insert into produse (cod, denumire) values(584,'Socket 423, 845 PRO, Intel 845, FSB400, SDRAM, ATX, UDMA 100, audio');  
insert into produse (cod, denumire) values(585,'GeForce3 Ti200 64MB DDR TV-OUT, GeForce3 Ti200, 64MB DDR, TV-OUT');  
insert into produse (cod, denumire) values(586,'GeForce3 Ti500 64MB DDR TV-OUT, GeForce3 Ti500, 64MB DDR, TV-OUT');  
insert into produse (cod, denumire) values(587,'Socket 370, 815EM PRO, Intel 815E, FSB133, SDRAM, mATX, UDMA 100, audio + video');  
insert into produse (cod, denumire) values(588,'Socket 370, 6368, VIA PLE133, FSB133, SDRAM, mATX, UDMA 100, audio, video + retea');  
insert into produse (cod, denumire) values(589,'Socket 370, 6337 lite, Intel 815EPT, FSB133, SDRAM, ATX, UDMA 100, audio');  
insert into produse (cod, denumire) values(590,'Socket A, K7T 266 PRO2-RU, VIA KT266A, FSB266, DDRAM, ATX, UDMA 100, audio, RAID IDE, USB 2.0');  
insert into produse (cod, denumire) values(591,'Socket 370, 815EPT PRO, Intel 815EPT, FSB133, SDRAM, ATX, UDMA 100, audio');  
insert into produse (cod, denumire) values(592,'GeForce2 MX 200 32MB TV-Out, GeForce2 MX 200, 32MB SDRAM, iesire video');  
insert into produse (cod, denumire) values(593,'Socket A, K7T Turbo2, VIA KT133A, FSB266, SDRAM, ATX, UDMA 100, audio');  
insert into produse (cod, denumire) values(594,'Socket A, K7T 266 PRO2 bulk, VIA KT266A, FSB266, DDRAM, ATX, UDMA 100, audio, bulk');  
insert into produse (cod, denumire) values(595,'GeForce2 MX 200 bulk, GeForce2 MX 200, 32MB SDRAM, bulk');  
insert into produse (cod, denumire) values(596,'Socket 478, 845 PRO2, Intel 845, FSB400, SDRAM, ATX, UDMA 100, audio');  
insert into produse (cod, denumire) values(597,'Socket 478, 850 PRO5, Intel 850, FSB400, RDRAM, ATX, UDMA 100, audio');  
insert into produse (cod, denumire) values(598,'Socket A, K7N 420 PRO, nVidia nForce 420, FSB266, DDRAM, ATX, UDMA 100, unitate audio de procesare, un itate grafica clasa GeForce2 MX integrata');  
insert into produse (cod, denumire) values(599,'Dual Socket 370, PRO266TD-R Master, VIA PRO266T, FSB133, DDRAM, ATX, UDMA 100, audio, RAID IDE');  
insert into produse (cod, denumire) values(600,'Socket A, 6340M, VIA KM133A, FSB266, SDRAM, mATX, UDMA 100, audio + video');  
insert into produse (cod, denumire) values(601,'EP 705H, 800x600, 1000 lumeni, DLP');  
insert into produse (cod, denumire) values(602,'EP 702, 800x600, 800 lumeni, DLP');  
insert into produse (cod, denumire) values(603,'EP 730, 1024x768 comprimata, 1100 lumeni, DLP');  
insert into produse (cod, denumire) values(604,'EP 585, 800x600, 500 lumeni');  
insert into produse (cod, denumire) values(605,'EzPro 550, 800x600, 300 lumeni');  
insert into produse (cod, denumire) values(606,'EP 735, 1024x768, 1100 lumeni, DLP');  
insert into produse (cod, denumire) values(607,'EP 610H, 800x600, 1250 lumeni');  
insert into produse (cod, denumire) values(608,'EP 715H, 1024x768, 1000 lumeni, DLP');  
insert into produse (cod, denumire) values(609,'EP 615H, 1024x768, 1250 lumeni');  
insert into produse (cod, denumire) values(610,'m505 Handheld, 8 MB (max. 72MB), color, USB');  
insert into produse (cod, denumire) values(611,'m500 Handheld, 8 MB (max. 72MB), monocrom, USB');  
insert into produse (cod, denumire) values(612,'m125 Handheld, 8 MB (max. 72MB), monocrom, USB');  
insert into produse (cod, denumire) values(613,'m105 Handheld, 8 MB, monocrom');  
insert into produse (cod, denumire) values(614,'Tastatura pentru m50x si m125');  
insert into produse (cod, denumire) values(615,'Leather Wallet Case pentru m50x');  
insert into produse (cod, denumire) values(616,'Belt Clip Case pentru m50x');  
insert into produse (cod, denumire) values(617,'Leather Carrying Case pentru m50x');  
insert into produse (cod, denumire) values(618,'Leather Carrying Case pentru m1xx');  
insert into produse (cod, denumire) values(619,'Facecover "Red"');  
insert into produse (cod, denumire) values(620,'Facecover "Azure"');  
insert into produse (cod, denumire) values(621,'Pachet 3 Stylus pentru m1xx');  
insert into produse (cod, denumire) values(622,'Blue Palmglove Case pentru m1xx');  
insert into produse (cod, denumire) values(623,'Facecover "Wood"');  
insert into produse (cod, denumire) values(624,'Pachet de 3 Stylus-uri pentru m50x');  
insert into produse (cod, denumire) values(625,'DC2000');  
insert into produse (cod, denumire) values(626,'DV option for DC1000, DC2000');  
insert into produse (cod, denumire) values(627,'DV500 PLUS');  
insert into produse (cod, denumire) values(628,'Studio PCTV, TV Tuner, PAL B/G, remote');  
insert into produse (cod, denumire) values(629,'DC1000-DV');  
insert into produse (cod, denumire) values(630,'Studio DV OEM');  
insert into produse (cod, denumire) values(631,'Pro-ONE');  
insert into produse (cod, denumire) values(632,'Studio PCTV PRO, TV Tuner w. FM tuner, PAL B/G, remote');  
insert into produse (cod, denumire) values(633,'PCTV SAT, SAT Receiver Digital');  
insert into produse (cod, denumire) values(634,'DV200');  
insert into produse (cod, denumire) values(635,'STUDIO DV PLUS');  
insert into produse (cod, denumire) values(636,'Studio Online');  
insert into produse (cod, denumire) values(637,'STUDIO DC10 Plus');  
insert into produse (cod, denumire) values(638,'King Pro 1000');  
insert into produse (cod, denumire) values(639,'Black Knight 500');  
insert into produse (cod, denumire) values(640,'King 625');  
insert into produse (cod, denumire) values(641,'King Office 520');  
insert into produse (cod, denumire) values(642,'King Pro 1500');  
insert into produse (cod, denumire) values(643,'SO DIMM SDRAM 128MB PC133');  
insert into produse (cod, denumire) values(644,'DIMM SDRAM 512MB PC133');  
insert into produse (cod, denumire) values(645,'Smart Media 128MB');  
insert into produse (cod, denumire) values(646,'Compact Flash 256MB');  
insert into produse (cod, denumire) values(647,'SO DIMM SDRAM 256MB PC100');  
insert into produse (cod, denumire) values(648,'Compact Flash 64MB');  
insert into produse (cod, denumire) values(649,'Smart Media 64MB');  
insert into produse (cod, denumire) values(650,'DIMM SDRAM 256MB PC133');  
insert into produse (cod, denumire) values(651,'DIMM SDRAM 128MB PC133');  
insert into produse (cod, denumire) values(652,'http://www.flamingo.ro/f.asp?id=2985');  
insert into produse (cod, denumire) values(653,'17" TF786FT, .25, DDC, OSD');  
insert into produse (cod, denumire) values(654,'LCD 18.1" TFT, TL812');  
insert into produse (cod, denumire) values(655,'19" TE988, .26dp, 95KHz, OSD');  
insert into produse (cod, denumire) values(656,'42" Plasma Display, PDP4202W, 16:9, Wall Mounting');  
insert into produse (cod, denumire) values(657,'17" TF770FT, .25dp, 72KHz, DDC, OSD, TCO99');  
insert into produse (cod, denumire) values(658,'17" TE770, .27dp, 72KHz, OSD');  
insert into produse (cod, denumire) values(659,'15" TE555, .28dp, 54KHz, OSD');  
insert into produse (cod, denumire) values(661,'LCD 15" TFT, TL550');  
insert into produse (cod, denumire) values(662,'RELISYS LCD 17');  
insert into produse (cod, denumire) values(663,'MP3 RF CAMERA');  
insert into produse (cod, denumire) values(664,'MP3 RF DISCMAN MCD650S');  
insert into produse (cod, denumire) values(665,'MP3 RF PLAYER');  
insert into produse (cod, denumire) values(666,'EZ CARD 10/100, SMC1244TX, PCI, UTP');  
insert into produse (cod, denumire) values(667,'EZ SWITCH 24 PORT, SMC-EZ1024DT, 10/100Mbps');  
insert into produse (cod, denumire) values(668,'EZ SWITCH 16 PORT, SMC-EZ1016DT, 10/100Mbps');  
insert into produse (cod, denumire) values(669,'7004BR, Barricade Broadband Router');  
insert into produse (cod, denumire) values(670,'2682W, Wireless Bridge');  
insert into produse (cod, denumire) values(671,'EZ CARD 10/100, SMC1255TX/WL, PCI, UTP');  
insert into produse (cod, denumire) values(672,'2652W, Wireless Access Point');  
insert into produse (cod, denumire) values(673,'2203USB/ETH, USB to Ethernet 10/100Mbps adapter');  
insert into produse (cod, denumire) values(674,'2620W, Wireless Access Point + PCMCIA Card');  
insert into produse (cod, denumire) values(675,'7008BR, Barricade Broadband Router');  
insert into produse (cod, denumire) values(676,'EZ SWITCH 8 PORT, SMC-EZ108DT, 10/100Mbps');  
insert into produse (cod, denumire) values(677,'EtherPower II CARD 10/100, SMC9432TX, PCI, UTP');  
insert into produse (cod, denumire) values(678,'EZ SWITCH 8 PORT, SMC-EZ108FDT, 10/100Mbps');  
insert into produse (cod, denumire) values(679,'EZ CARDBUS 10/100, SMC8035TX, PCMCIA, 100MHz, UTP');  
insert into produse (cod, denumire) values(680,'2632W, Wireless PCMCIA Card');  
insert into produse (cod, denumire) values(681,'2602W, Wireless PCI Card');  
insert into produse (cod, denumire) values(682,'2662W, Wireless Adaptor USB');  
insert into produse (cod, denumire) values(683,'DDS DRIVE SDT-S11000, 20/40GB, 3.5", UltraWideSCSI, externa');  
insert into produse (cod, denumire) values(684,'DDS 4 DRIVE SDT-11000, 20/40GB, 3.5", UltraWideSCSI SE+LVD, interna');  
insert into produse (cod, denumire) values(685,'SONY HEADPHONE 301LP');  
insert into produse (cod, denumire) values(686,'FDD 3,5", 1.44MB, interna, IDE');  
insert into produse (cod, denumire) values(687,'SONY HEADPHONE CD280');  
insert into produse (cod, denumire) values(688,'SONY MICROFON V420');  
insert into produse (cod, denumire) values(689,'SONY HEADPHONE G52LP');  
insert into produse (cod, denumire) values(690,'CD-R SONY');  
insert into produse (cod, denumire) values(691,'DDS 3 DRIVE SDT-S9000, 12/24GB, 3.5", SCSI II, extern');  
insert into produse (cod, denumire) values(692,'DVD-ROM 16x, interna, IDE, retail');  
insert into produse (cod, denumire) values(693,'SONY HEADPHONE CD380');  
insert into produse (cod, denumire) values(694,'DDS Media DDS 3, 12GB/24GB');  
insert into produse (cod, denumire) values(695,'MEDIA MO 5.25" 2.6GB');  
insert into produse (cod, denumire) values(696,'DDS Media DDS 2, 4GB/8GB');  
insert into produse (cod, denumire) values(697,'DDS 2 DRIVE SDT-7000R, 4/8GB, 3.5", SCSI II, interna');  
insert into produse (cod, denumire) values(698,'DDS 3 DRIVE SDT-9000R, 12/24GB, 3.5", SCSI, interna');  
insert into produse (cod, denumire) values(699,'SONY DDS CLEANING TAPE');  
insert into produse (cod, denumire) values(700,'SONY HEADPHONE 101LP');  
insert into produse (cod, denumire) values(701,'SONY HEADPHONE P180');  
insert into produse (cod, denumire) values(702,'SONY HEADPHONE E828LP');  
insert into produse (cod, denumire) values(703,'Microfon F-V220');  
insert into produse (cod, denumire) values(704,'SONY MEDIA MO 3.5" 640MB');  
insert into produse (cod, denumire) values(705,'SONY MICROFON V-120');  
insert into produse (cod, denumire) values(706,'CD-R 80, pachet de 5 buc.');  
insert into produse (cod, denumire) values(707,'MEDIA MO 3.5" 230MB');  
insert into produse (cod, denumire) values(708,'CD-RW Media SONY');  
insert into produse (cod, denumire) values(709,'SONY HEADPHONE 201V');  
insert into produse (cod, denumire) values(710,'SONY HEADPHONE W24V');  
insert into produse (cod, denumire) values(711,'SONY HEADPHONE W08L');  
insert into produse (cod, denumire) values(712,'CD-R 80 SONY');  
insert into produse (cod, denumire) values(713,'SONY HEADPHONE E818LP');  
insert into produse (cod, denumire) values(714,'SONY MICROFON V-120');  
insert into produse (cod, denumire) values(715,'LCD 15.1" TFT, SDM-M51B');  
insert into produse (cod, denumire) values(716,'Baterie 1000 mAh Z5');  
insert into produse (cod, denumire) values(717,'Cablu conectare PC - Z5');  
insert into produse (cod, denumire) values(718,'Cablu USB J5');  
insert into produse (cod, denumire) values(719,'Car holder pentru Z5');  
insert into produse (cod, denumire) values(720,'Headset pentru Z5');  
insert into produse (cod, denumire) values(721,'Travel charger pentru Z5');  
insert into produse (cod, denumire) values(722,'VAIO PCG-FX101 C600/64MB/10GB/13,3"TFT/CD24X/FaxModem/WinME');  
insert into produse (cod, denumire) values(723,'PS MEMORY CARD PS1');  
insert into produse (cod, denumire) values(724,'VAIO PCG-R600HEP P850/128MB/20GB/12,1"TFT/FaxModem/LAN/WinXP Pro');  
insert into produse (cod, denumire) values(725,'PS MULTI TAP SCPH 1070');  
insert into produse (cod, denumire) values(726,'SONY MICROFON V-220');  
insert into produse (cod, denumire) values(727,'SONY AV DISCMAN TUNER');  
insert into produse (cod, denumire) values(728,'PS CONSOLE ONE');  
insert into produse (cod, denumire) values(729,'PS CONSOLE PS2');  
insert into produse (cod, denumire) values(730,'VPL-PX31, 3xLCD, 1024x768, 2800 lumeni');  
insert into produse (cod, denumire) values(731,'VPL-VW10HT, 3xLCD, 1366x768, 1000 lumeni, Home Cinema');  
insert into produse (cod, denumire) values(732,'VPL-HS1, 3xLCD, Side Shot, Slot Memory Stick');  
insert into produse (cod, denumire) values(733,'VPL CS4, 3xLCD, 800x600, 1000 lumeni');  
insert into produse (cod, denumire) values(734,'VAIO PCG-SR21K P650/64MB/10GB/10,4"TFT/CD16X/audio/FaxModem/Win2K');  
insert into produse (cod, denumire) values(735,'LCD 15.1"');  
insert into produse (cod, denumire) values(736,'SONY HEADPHONE IF230RKEE');  
insert into produse (cod, denumire) values(737,'SONY HEADPHONE CD480');  
insert into produse (cod, denumire) values(738,'SONY HEADPHONE CD780');  
insert into produse (cod, denumire) values(739,'17" Multiscan E230 FD Tinitron, 0.24-0.25dp, 85KHz, TCO99');  
insert into produse (cod, denumire) values(740,'19" FD TRINITRON, .24dp, Multiscan E400, superflat, 96 KHz, TCO 99');  
insert into produse (cod, denumire) values(741,'19" Multiscan G420 FD Trinitron , 0.24-0.25dp, 110KHz, TCO99');  
insert into produse (cod, denumire) values(742,'17" Multiscan E530 FD Tinitron, 0.24dp, 109KHz, TCO99');  
insert into produse (cod, denumire) values(743,'21" FD TRINITRON, .24dp, Multiscan G520, superflat, 130 kHz, TCO 99');  
insert into produse (cod, denumire) values(744,'PCMCIA conectare notebook - Z5');  
insert into produse (cod, denumire) values(745,'24" TRINITRON, .25dp, Multiscan FW900, 16:10, TCO 99');  
insert into produse (cod, denumire) values(746,'SONY HEADPHONE IF130KEE');  
insert into produse (cod, denumire) values(747,'LCD 15.1" TFT, SDM-M51D');  
insert into produse (cod, denumire) values(748,'LCD 16" TFT, SDM-M61');  
insert into produse (cod, denumire) values(749,'LCD 15" TFT, SDM-N50PS, media engine, pivot');  
insert into produse (cod, denumire) values(750,'LCD 18.1" TFT, SDM-M81');  
insert into produse (cod, denumire) values(751,'PLASMA 42');  
insert into produse (cod, denumire) values(752,'PS MEMORY CARD PS2 8MB');  
insert into produse (cod, denumire) values(753,'PS G-CON 45 GUN SLEH00007');  
insert into produse (cod, denumire) values(754,'PS DUAL SHOCK PS1');  
insert into produse (cod, denumire) values(755,'21" FD TRINITRON, .22dp, Multiscan F520, superflat, 137 kHz, TCO 99');  
insert into produse (cod, denumire) values(756,'SONY Handycam DCR TRV30');  
insert into produse (cod, denumire) values(757,'CRX175A, interna, IDE, bulk');  
insert into produse (cod, denumire) values(758,'Memory Stick 64 MB (MSA-64A)');  
insert into produse (cod, denumire) values(759,'MAVICA ADAPTOR MS-FLOPPY');  
insert into produse (cod, denumire) values(760,'MAVICA ADAPTOR MS-USB');  
insert into produse (cod, denumire) values(761,'MAVICA ADAPTOR MS-PCMCIA');  
insert into produse (cod, denumire) values(762,'Memory Stick 32MB (MSA-32A)');  
insert into produse (cod, denumire) values(763,'Memory Stick 128MB (MSA-128A)');  
insert into produse (cod, denumire) values(764,'SONY Hanydcam DCR PC110');  
insert into produse (cod, denumire) values(765,'SONY VIDEO PRINTER DPP-SV55');  
insert into produse (cod, denumire) values(766,'Sony Handycam DCR PC115');  
insert into produse (cod, denumire) values(767,'SONY Handycam DCR TRV900E');  
insert into produse (cod, denumire) values(768,'SONY Handycam DCR VX2000');  
insert into produse (cod, denumire) values(769,'DVD-ROM 16x, interna, IDE, bulk');  
insert into produse (cod, denumire) values(770,'CRX 10U-RP, 4x/4x/6x, externa, USB, MP3 player, retail');  
insert into produse (cod, denumire) values(771,'CRX175A-RP, interna, EIDE, retail');  
insert into produse (cod, denumire) values(772,'CRX 1611E-RP, 16x/10x/40x, interna, EIDE, retail');  
insert into produse (cod, denumire) values(773,'Memory Stick 16MB (MSA-16A)');  
insert into produse (cod, denumire) values(774,'SONY Handycam DCR TRV15');  
insert into produse (cod, denumire) values(775,'AIT SDX 400C/R, 35/90GB, 3.5", UltraWideSCSI SE+LVD, intern');  
insert into produse (cod, denumire) values(776,'Handycam DCR PC6');  
insert into produse (cod, denumire) values(777,'DDS 2 DRIVE SDT-S7200, 4/8GB, 3.5", SCSI, extern');  
insert into produse (cod, denumire) values(778,'SONY Handycam DCR TRV17');  
insert into produse (cod, denumire) values(779,'SONY Handycam DCR-TRV730');  
insert into produse (cod, denumire) values(780,'SONY Handycam DCR PC9E');  
insert into produse (cod, denumire) values(781,'MOUSE ADAPTOR MS-USB');  
insert into produse (cod, denumire) values(782,'SONY Handycam DCR-TRV330');  
insert into produse (cod, denumire) values(783,'CRX 75A-RP, 8x/4x/24x, externa, PCMCIA, retail');  
insert into produse (cod, denumire) values(784,'SONY Handycam DCR-TRV830');  
insert into produse (cod, denumire) values(785,'SONY Handycam DCR-TRV230');  
insert into produse (cod, denumire) values(786,'SONY Handycam DCR-TRV130');  
insert into produse (cod, denumire) values(787,'SONY Handycam CCD-TRV98');  
insert into produse (cod, denumire) values(788,'SONY Handycam CCD-TRV78');  
insert into produse (cod, denumire) values(789,'SONY Handycam CCD-TRV59');  
insert into produse (cod, denumire) values(790,'SONY Handycam CCD-TR728');  
insert into produse (cod, denumire) values(791,'SONY Handycam TRV330 STUDIO');  
insert into produse (cod, denumire) values(792,'Dischete 3,5" SONY');  
insert into produse (cod, denumire) values(793,'Digital Camera DSC-S75, memory stick');  
insert into produse (cod, denumire) values(794,'Digital Camera MAVICA MVC-FD92, floppy');  
insert into produse (cod, denumire) values(795,'Digital Camera MAVICA MVC-FD87, floppy');  
insert into produse (cod, denumire) values(796,'Digital Camera MAVICA MVC-FD75, floppy');  
insert into produse (cod, denumire) values(797,'Digital Camera DSC-P50, memory stick');  
insert into produse (cod, denumire) values(798,'CD-ROM 52X, IDE, bulk');  
insert into produse (cod, denumire) values(799,'Digital Camera DSC-S85, Memory Stick');  
insert into produse (cod, denumire) values(800,'SONY CMD-J5');  
insert into produse (cod, denumire) values(801,'SONY CMD-Z5');  
insert into produse (cod, denumire) values(802,'Unitate magneto-optica SMO-F561, 9.1GB, 5.25", SCSI, intern');  
insert into produse (cod, denumire) values(803,'Unitate magneto-optica RMO-S561, 9.1GB, 5.25", SCSI, extern');  
insert into produse (cod, denumire) values(804,'AIT SDX 500C/R, 50/130GB, 3.5", UltraWideSCSI SE+LVD, interna');  
insert into produse (cod, denumire) values(805,'DDS DRIVE TSL-S11000, 160/320GB, 3.5", UltraWide SCSI SE+LVD, extern');  
insert into produse (cod, denumire) values(806,'AIT 130E-SB, 50/130GB, 3.5", UltraWideSCSI SE+LVD, externa');  
insert into produse (cod, denumire) values(807,'Unitate magneto-optica RMO-S551, 5.2GB, 5.25", SCSI, extern');  
insert into produse (cod, denumire) values(808,'Unitate magneto-optica SMO-F551, 5.2GB, 5.25", SCSI, intern');  
insert into produse (cod, denumire) values(809,'Digital Camera Cyber-shot DSC-P30, Memory Stick');  
insert into produse (cod, denumire) values(810,'Digital Camera MAVICA CD-200');  
insert into produse (cod, denumire) values(811,'Digital Camera Cyber-shot DSC-P20, Memory Stick');  
insert into produse (cod, denumire) values(812,'Digital Camera MAVICA MVC-FD97, floppy');  
insert into produse (cod, denumire) values(813,'Digital Camera MAVICA CD-300');  
insert into produse (cod, denumire) values(814,'PM-Traveller');  
insert into produse (cod, denumire) values(815,'FDD 3,5", 1.44MB, externa, USB');  
insert into produse (cod, denumire) values(816,'DVD ROM 8x pentru notebook, interna, EIDE');  
insert into produse (cod, denumire) values(817,'PM-500-B');  
insert into produse (cod, denumire) values(818,'CD-210PU 10X portabil, USB');  
insert into produse (cod, denumire) values(819,'CD-224PE 24X pentru notebook, externa, PCMCIA, retail');  
insert into produse (cod, denumire) values(820,'PM-2000');  
insert into produse (cod, denumire) values(821,'CD-224E 24X pentru notebook, interna, EIDE');  
insert into produse (cod, denumire) values(822,'PM-1500');  
insert into produse (cod, denumire) values(823,'TFT SoundLine');  
insert into produse (cod, denumire) values(824,'PM260');  
insert into produse (cod, denumire) values(825,'PM140');  
insert into produse (cod, denumire) values(826,'CD-540 40X, interna, EIDE, bulk');  
insert into produse (cod, denumire) values(827,'PM300');  
insert into produse (cod, denumire) values(828,'CD-RW Media TEAC');  
insert into produse (cod, denumire) values(829,'PM80');  
insert into produse (cod, denumire) values(830,'PM60');  
insert into produse (cod, denumire) values(831,'CD-R Teac');  
insert into produse (cod, denumire) values(832,'FDD 3,5", 1.44MB, interna, IDE');  
insert into produse (cod, denumire) values(833,'CD-W524E 24x / 10x / 40x, interna, IDE, bulk');  
insert into produse (cod, denumire) values(834,'TEAC FDD SCSI');  
insert into produse (cod, denumire) values(835,'CD-R Duplicator 4, 12x/10x/32x, functioneaza fara conectare la PC');  
insert into produse (cod, denumire) values(836,'Satellite 1800-100 C800/128MB/15GB/13.3"TFT/CD24X/audio/FaxModem/WinME');  
insert into produse (cod, denumire) values(837,'Satellite 1800-204 C1000/192MB/20GB/13,3"TFT/DVD8X/audio/FaxModem/LAN/WinXP Home');  
insert into produse (cod, denumire) values(838,'Smart INT 1400 RM');  
insert into produse (cod, denumire) values(839,'Smart INT 3000');  
insert into produse (cod, denumire) values(840,'Smart INT 2200');  
insert into produse (cod, denumire) values(841,'Surge Suppressor');  
insert into produse (cod, denumire) values(842,'Smart INT 1400');  
insert into produse (cod, denumire) values(843,'Smart INT 1000');  
insert into produse (cod, denumire) values(844,'Internet 500I');  
insert into produse (cod, denumire) values(845,'Internet 700I');  
insert into produse (cod, denumire) values(846,'US Robotics Wireless Access Point');  
insert into produse (cod, denumire) values(847,'US Robotics Wireless Access PCI Adapter');  
insert into produse (cod, denumire) values(848,'US Robotics Network Card');  
insert into produse (cod, denumire) values(849,'US Robotics Wireless Access PC Card');  
insert into produse (cod, denumire) values(850,'US Robotics Courier V. Everything 56K External');  
insert into produse (cod, denumire) values(851,'US Robotics ISDN External Pro TA');  
insert into produse (cod, denumire) values(852,'Courier I-Modem');  
insert into produse (cod, denumire) values(853,'US Robotics 56k MESSAGE extern');  
insert into produse (cod, denumire) values(854,'US Robotics 56k extern');  
insert into produse (cod, denumire) values(855,'US Robotics 56k PCI, RETAIL');  
insert into produse (cod, denumire) values(856,'US Robotics Cable Modem');  
insert into produse (cod, denumire) values(857,'US Robotics 56k PCMCIA XJACK');  
insert into produse (cod, denumire) values(858,'Cablu audio stereo RCA, 1.5m (plug) (Gold) (V7158)');  
insert into produse (cod, denumire) values(859,'Derulator casete video VHS (V2420)');  
insert into produse (cod, denumire) values(860,'Geanta "Tramp 155" (V2359)');  
insert into produse (cod, denumire) values(861,'Cablu audio/video, stereo, SCART <-> RCA/S-Video, 2m (HQ), (V4944)');  
insert into produse (cod, denumire) values(862,'Cablu optic TOS/3.5mm jack, 1.5m (V3126)');  
insert into produse (cod, denumire) values(863,'Cablu S-Video, 1.5m (Gold) (V7164)');  
insert into produse (cod, denumire) values(864,'Cablu pt. switch tastatura, AT (V4590)');  
insert into produse (cod, denumire) values(865,'Cablu optic TOS/TOS, 1.5m (V3123)');  
insert into produse (cod, denumire) values(866,'Cablu FireWire 6pini/6pini, 2m (V4397)');  
insert into produse (cod, denumire) values(867,'Trepied pentru microfon (V9200)');  
insert into produse (cod, denumire) values(868,'Kit cabluri audio/video (V5188)');  
insert into produse (cod, denumire) values(869,'Cablu audio/video, stereo, SCART, 11pini, 1m (HQ) (V6964)');  
insert into produse (cod, denumire) values(870,'Cablu digital coaxial, 1.5m (Gold) (V7183)');  
insert into produse (cod, denumire) values(871,'Derulator casete video 8mm (V2412)');  
insert into produse (cod, denumire) values(872,'Cablu audio/video, stereo, RCA, 1.5m (plug) (Gold) (V7162)');  
insert into produse (cod, denumire) values(873,'Adaptor plastic pentru HDD 3.5"->5.25" (V3884)');  
insert into produse (cod, denumire) values(874,'Geanta pt. walkman (V2481)');  
insert into produse (cod, denumire) values(875,'Mixer audio MX-730 EQ, 6 canale (V9730)');  
insert into produse (cod, denumire) values(876,'Audio mixer MX360 (V9497)');  
insert into produse (cod, denumire) values(877,'Cooler slot 5.25" (V3777)');  
insert into produse (cod, denumire) values(878,'Adaptor audio/video RCA->SCART (V6908)');  
insert into produse (cod, denumire) values(879,'Adaptor audio/video SCART->RCA (V6909)');  
insert into produse (cod, denumire) values(880,'Cablu SCSI intern, 5 conectori (V2937)');  
insert into produse (cod, denumire) values(881,'Adaptor audio/video bidirectional RCA/S-Video<->SCART (V6910)');  
insert into produse (cod, denumire) values(882,'Cablu S-Video - extensie 2m (V4941)');  
insert into produse (cod, denumire) values(883,'Adaptor casete S-VHS-C la VHS (V1038)');  
insert into produse (cod, denumire) values(884,'Adaptor casete S-VHS-C la VHS (V1007)');  
insert into produse (cod, denumire) values(885,'TV-wall mounting stand, max. 30 kg (V2158)');  
insert into produse (cod, denumire) values(886,'Cablu FireWire 4pini/6pini, 2m (V3745)');  
insert into produse (cod, denumire) values(887,'Cablu audio/video, stereo, SCART, 1.5m (Gold) (V7154)');  
insert into produse (cod, denumire) values(888,'Terminator activ intern Wide SCSI (V2071)');  
insert into produse (cod, denumire) values(889,'Adaptor plastic pentru FDD 3.5"->5.25" (V3885)');  
insert into produse (cod, denumire) values(890,'Cablu audio stereo RCA - extensie 2m (V4303)');  
insert into produse (cod, denumire) values(891,'FM headphones set on 863 MHz (V8486)');  
insert into produse (cod, denumire) values(892,'Cablu S-Video, 2m (V4940)');  
insert into produse (cod, denumire) values(893,'Trepied "VS 121" (V1427)');  
insert into produse (cod, denumire) values(894,'Geanta "Tramp 300" (V1336)');  
insert into produse (cod, denumire) values(895,'Geanta "Tramp 260" (V1376)');  
insert into produse (cod, denumire) values(896,'Geanta "Tramp 220 P" (V1604)');  
insert into produse (cod, denumire) values(897,'Cablu video RCA, 2m (plug) (V6952)');  
insert into produse (cod, denumire) values(898,'Cablu audio stereo RCA, 1.5m (plug) (V4301)');  
insert into produse (cod, denumire) values(899,'TV-wall mounting stand, max. 50 kg (V2192)');  
insert into produse (cod, denumire) values(900,'MMC Card mem 16mb - pentru PALM (V9021)');  
insert into produse (cod, denumire) values(901,'Cablu audio stereo jack-RCA, 1.5m (plug) (V4509)');  
insert into produse (cod, denumire) values(902,'Cablu audio/video, stereo, SCART, 1.5m (V5180)');  
insert into produse (cod, denumire) values(903,'Cablu audio/video, mono, RCA, 2m (plug) (V4903)');  
insert into produse (cod, denumire) values(904,'Geanta "Palmline 220" (V1808)');  
insert into produse (cod, denumire) values(905,'Cablu BNC mufat - 10m (V3477)');  
insert into produse (cod, denumire) values(906,'Cablu BNC mufat - 5m (V3476)');  
insert into produse (cod, denumire) values(907,'Cablu audio/video, stereo, RCA, 2m (plug) (V4914)');  
insert into produse (cod, denumire) values(908,'Monitor filter 17 zoll FMO17 (V9348)');  
insert into produse (cod, denumire) values(909,'Casti audio radio cordless FMH 7700, 433 MHz, 100m (V8487)');  
insert into produse (cod, denumire) values(910,'Cablu audio stereo RCA - extensie 5m (V4316)');  
insert into produse (cod, denumire) values(911,'Gel wrist mouse pad (V9504)');  
insert into produse (cod, denumire) values(912,'CD-RW ALADAR 16x/10x/40x, interna, soft, EIDE, bulk');  
insert into produse (cod, denumire) values(913,'20.0GB, WD-200AB, RPM 5400, UATA/100');  
insert into produse (cod, denumire) values(914,'100.0GB WD-1000BB, RPM 7200, UATA/100');  
insert into produse (cod, denumire) values(915,'80.0GB WD-800BB, RPM 7200, UATA/100');  
insert into produse (cod, denumire) values(916,'60.0GB WD-600BB, RPM 7200, UATA/100');  
insert into produse (cod, denumire) values(917,'40.0GB WD-400BB, RPM 7200, UATA/100');  
insert into produse (cod, denumire) values(918,'30.0GB WD-300BB, RPM 7200, UATA/100');  
insert into produse (cod, denumire) values(919,'20.0GB WD-200BB, RPM 7200, UATA/100');  
insert into produse (cod, denumire) values(920,'40.0GB WD-400AB, RPM 5400, UATA/100');  
insert into produse (cod, denumire) values(921,'Keyboard PSR-170');  
insert into produse (cod, denumire) values(922,'Plug-in Board PLG150-AN(SW 1000)');  
insert into produse (cod, denumire) values(923,'Plug-in Board PLG-150-PF(SW1000)');  
insert into produse (cod, denumire) values(924,'Plug-in Board PLG150-DX(SW1000)');  
insert into produse (cod, denumire) values(925,'Sound Card SW1000');  
insert into produse (cod, denumire) values(926,'Keyboard PSS-15');  
insert into produse (cod, denumire) values(927,'DJX-IIB');  
insert into produse (cod, denumire) values(928,'YST-MS30, subwoofer');  
insert into produse (cod, denumire) values(929,'Keyboard PSR-260');  
insert into produse (cod, denumire) values(930,'YST-MS201, subwoofer');  
insert into produse (cod, denumire) values(931,'Keyboard EZ20');  
insert into produse (cod, denumire) values(932,'DJX-II');  
insert into produse (cod, denumire) values(933,'Keyboard PSR-280');  
insert into produse (cod, denumire) values(934,'YST-M55D, Subwoofer, USB');  
insert into produse (cod, denumire) values(935,'Keyboard PSR-74');  
insert into produse (cod, denumire) values(936,'Generator de tonuri MU15');  
insert into produse (cod, denumire) values(937,'Plug-in Board PLG-150-VL(SW1000)');  
insert into produse (cod, denumire) values(938,'YST-MS35D Black, subwoofer, USB');  
insert into produse (cod, denumire) values(939,'CRW 2200E B10, 20x/10x/40x, interna, IDE, bulk');  
insert into produse (cod, denumire) values(940,'CD-RW CRW 2200E VK, 20x/10x/40x, interna, IDE, retail');  
insert into produse (cod, denumire) values(941,'Stand SL2');  
insert into produse (cod, denumire) values(942,'CRW 2200UX VK, 20x/10x/40x, externa, USB, retail');  
insert into produse (cod, denumire) values(943,'CRW2200SX VK, 20x/10x/40x, externa, SCSI, retail');  
insert into produse (cod, denumire) values(944,'CRW 2200IX VK, 20x/10x/40x, extern, FireWire, retail');  
insert into produse (cod, denumire) values(945,'Sampling Unit SU200');  
insert into produse (cod, denumire) values(946,'MIDI Cable 15M');  
insert into produse (cod, denumire) values(947,'MIDI Cable MDC-01');  
insert into produse (cod, denumire) values(948,'Keyboard PSS-9');  
insert into produse (cod, denumire) values(949,'Kit chitara electrica EG112 + boxa monitor GA10 7W');  
insert into produse (cod, denumire) values(950,'Synthesiser S03');  
insert into produse (cod, denumire) values(951,'Desktop Control Synthesiser AN200');  
insert into produse (cod, denumire) values(952,'Desktop Control Synthesizer DX200');  
insert into produse (cod, denumire) values(953,'Keyboard PSR-350');  
insert into produse (cod, denumire) values(954,'Keyboard PSR-GX76');  
insert into produse (cod, denumire) values(955,'Keyboard PSS-7');  
insert into produse (cod, denumire) values(956,'Stand L4GC');  
insert into produse (cod, denumire) values(1101,'Accesorii');  
insert into produse (cod, denumire) values(1003,'Accesorii audio-video');  
insert into produse (cod, denumire) values(1004,'Accesorii de birou');  
insert into produse (cod, denumire) values(1001,'Accesorii GSM');  
insert into produse (cod, denumire) values(1005,'Accesorii retea');  
insert into produse (cod, denumire) values(1006,'Accesorii storage');  
insert into produse (cod, denumire) values(1007,'Accesorii diverse');  
insert into produse (cod, denumire) values(1009,'Adaptoare');  
insert into produse (cod, denumire) values(1014,'Cabluri alimentare');  
insert into produse (cod, denumire) values(1015,'Cabluri audio-video');  
insert into produse (cod, denumire) values(1016,'Cabluri de date');  
insert into produse (cod, denumire) values(1019,'Camere foto/video');  
insert into produse (cod, denumire) values(1026,'Coolere');  
insert into produse (cod, denumire) values(1028,'Diverse');  
insert into produse (cod, denumire) values(1047,'Notebook');  
insert into produse (cod, denumire) values(1102,'Console');  
insert into produse (cod, denumire) values(1002,'Accesorii PS');  
insert into produse (cod, denumire) values(1053,'PlayStation');  
insert into produse (cod, denumire) values(1103,'Electronice');  
insert into produse (cod, denumire) values(1049,'Personal audio');  
insert into produse (cod, denumire) values(1104,'GSM');  
insert into produse (cod, denumire) values(1064,'Telefoane GSM');  
insert into produse (cod, denumire) values(1105,'Imprimante');  
insert into produse (cod, denumire) values(1011,'All-In-One');  
insert into produse (cod, denumire) values(1034,'InkJet');  
insert into produse (cod, denumire) values(1037,'Laser');  
insert into produse (cod, denumire) values(1038,'Matriceale');  
insert into produse (cod, denumire) values(1106,'Key components');  
insert into produse (cod, denumire) values(1022,'Carcase');  
insert into produse (cod, denumire) values(1025,'Controllere SCSI, RAID');  
insert into produse (cod, denumire) values(1041,'Memorii');  
insert into produse (cod, denumire) values(1050,'Placi de baza');  
insert into produse (cod, denumire) values(1052,'Placi video');  
insert into produse (cod, denumire) values(1055,'Procesoare');  
insert into produse (cod, denumire) values(1107,'Media + Consumabile');  
insert into produse (cod, denumire) values(1013,'CD-R/CD-RW/DVD-RAM');  
insert into produse (cod, denumire) values(1027,'Dischete');  
insert into produse (cod, denumire) values(1033,'Imprimante, fax, copiatoare');  
insert into produse (cod, denumire) values(1039,'Medii de stocare portabile');  
insert into produse (cod, denumire) values(1040,'Medii de stocare profesionale');  
insert into produse (cod, denumire) values(1108,'Monitoare');  
insert into produse (cod, denumire) values(1044,'Monitoare CRT');  
insert into produse (cod, denumire) values(1045,'Monitoare LCD');  
insert into produse (cod, denumire) values(1109,'Multimedia');  
insert into produse (cod, denumire) values(1012,'Boxe');  
insert into produse (cod, denumire) values(1024,'Clape MIDI + DJ Tools');  
insert into produse (cod, denumire) values(1036,'Kit-uri multimedia');  
insert into produse (cod, denumire) values(1042,'Microfoane, casti');  
insert into produse (cod, denumire) values(1051,'Placi de sunet');  
insert into produse (cod, denumire) values(1054,'Playere audio portabile');  
insert into produse (cod, denumire) values(1062,'TV tunere');  
insert into produse (cod, denumire) values(1110,'Networking');  
insert into produse (cod, denumire) values(1010,'Adaptoare retea');  
insert into produse (cod, denumire) values(1032,'Hub-uri');  
insert into produse (cod, denumire) values(1043,'Modemuri');  
insert into produse (cod, denumire) values(1057,'Router-e');  
insert into produse (cod, denumire) values(1061,'Switch-uri');  
insert into produse (cod, denumire) values(1071,'Wireless');  
insert into produse (cod, denumire) values(1111,'Periferice');  
insert into produse (cod, denumire) values(1021,'Camere web');  
insert into produse (cod, denumire) values(1023,'Cititoare coduri de bare');  
insert into produse (cod, denumire) values(1046,'Mouse/trackball/tablete grafice');  
insert into produse (cod, denumire) values(1048,'Periferice pentru jocuri');  
insert into produse (cod, denumire) values(1058,'Scanere');  
insert into produse (cod, denumire) values(1063,'Tastaturi');  
insert into produse (cod, denumire) values(1065,'UPS');  
insert into produse (cod, denumire) values(1112,'Sisteme');  
insert into produse (cod, denumire) values(1017,'Calculatoare');  
insert into produse (cod, denumire) values(1029,'Handheld');  
insert into produse (cod, denumire) values(1113,'Software');  
insert into produse (cod, denumire) values(1035,'Jocuri');  
insert into produse (cod, denumire) values(1070,'Utilitare');  
insert into produse (cod, denumire) values(1114,'Storage');  
insert into produse (cod, denumire) values(1030,'Hard discuri');  
insert into produse (cod, denumire) values(1031,'Hard discuri SCSI');  
insert into produse (cod, denumire) values(1059,'Solutii de stocare portabile');  
insert into produse (cod, denumire) values(1060,'Solutii de stocare profesionale');  
insert into produse (cod, denumire) values(1066,'Unitati CD-ROM');  
insert into produse (cod, denumire) values(1067,'Unitati CD-RW');  
insert into produse (cod, denumire) values(1068,'Unitati DVD');  
insert into produse (cod, denumire) values(1069,'Unitati Floppy');  
insert into produse (cod, denumire) values(1115,'Video');  
insert into produse (cod, denumire) values(1008,'Achizitie/editare video');  
insert into produse (cod, denumire) values(1018,'Camere foto digitale');  
insert into produse (cod, denumire) values(1020,'Camere video');  
insert into produse (cod, denumire) values(1056,'Proiectoare');  
